import * as T from 'three';
import {RoundedBoxGeometry} from 'three/addons/geometries/RoundedBoxGeometry.js';
import {mergeGeometries} from 'three/addons/utils/BufferGeometryUtils.js';
export type V=[number,number,number];
export type Mat=T.MeshStandardMaterial|T.MeshPhysicalMaterial;
export class Construction{
 private materials=new Map<string,Mat>();
 private textures=new Map<string,T.DataTexture>();
 private surface(kind:string){let map=this.textures.get(kind);if(map)return map;const size=64,data=new Uint8Array(size*size*4);for(let y=0;y<size;y++)for(let x=0;x<size;x++){const hash=((x*73+y*139+x*y*11)%97)/97;const weave=kind==='cloth'?((x%4===0||y%4===0)?-.09:.025):0;const v=Math.round((.82+hash*.16+weave)*255),i=(y*size+x)*4;data[i]=data[i+1]=data[i+2]=v;data[i+3]=255;}map=new T.DataTexture(data,size,size);map.wrapS=map.wrapT=T.RepeatWrapping;map.repeat.set(3,3);map.magFilter=T.LinearFilter;map.minFilter=T.LinearMipmapLinearFilter;map.generateMipmaps=true;map.needsUpdate=true;this.textures.set(kind,map);return map;}

 mat(color:number,kind:'cloth'|'armor'|'leather'|'skin'|'hair'|'stone'|'energy'|'shell'|'metal'='cloth',intensity=.7){
  const key=`${color}:${kind}:${intensity}`;let m=this.materials.get(key);if(m)return m;
  const settings={color,roughness:({cloth:.94,armor:.38,leather:.63,skin:.78,hair:.54,stone:1,energy:.28,shell:.28,metal:.3})[kind],metalness:({cloth:0,armor:.62,leather:.08,skin:0,hair:.02,stone:0,energy:.3,shell:.52,metal:.8})[kind]};
  m=kind==='shell'?new T.MeshPhysicalMaterial({...settings,clearcoat:.7,clearcoatRoughness:.3,iridescence:.22,iridescenceIOR:1.3}):new T.MeshStandardMaterial(settings);
  if(['cloth','leather','stone'].includes(kind)){const texture=this.surface(kind);m.map=texture;m.bumpMap=texture;m.bumpScale=kind==='stone'?.022:.005;m.roughnessMap=texture;}m.name=key;if(kind==='energy'){m.emissive.setHex(color);m.emissiveIntensity=intensity;}this.materials.set(key,m);return m;
 }
 mesh(parent:T.Object3D,geo:T.BufferGeometry,mat:Mat,p:V=[0,0,0],rotation:V=[0,0,0]){const m=new T.Mesh(geo,mat);m.position.set(...p);m.rotation.set(...rotation);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m;}
 oval(parent:T.Object3D,size:V,mat:Mat,p:V=[0,0,0],rotation:V=[0,0,0],segments=14){const geo=new T.SphereGeometry(1,segments,10);geo.scale(size[0],size[1],size[2]);return this.mesh(parent,geo,mat,p,rotation);}
 round(parent:T.Object3D,size:V,mat:Mat,p:V=[0,0,0],rotation:V=[0,0,0],radius=.04){return this.mesh(parent,new RoundedBoxGeometry(...size,2,Math.min(radius,...size.map(n=>n*.45))),mat,p,rotation);}
 profile(parent:T.Object3D,rows:[number,number,number][],mat:Mat,p:V=[0,0,0],segments=16){rows=[...rows].sort((a,b)=>a[0]-b[0]);const pts:number[]=[],uv:number[]=[],indices:number[]=[];rows.forEach(([y,rx,rz],j)=>{for(let i=0;i<=segments;i++){const a=i/segments*Math.PI*2;pts.push(Math.sin(a)*rx,y,Math.cos(a)*rz);uv.push(i/segments,j/(rows.length-1));}});for(let j=0;j<rows.length-1;j++)for(let i=0;i<segments;i++){const a=j*(segments+1)+i,b=a+segments+1;indices.push(a,a+1,b,b,a+1,b+1);}const geo=new T.BufferGeometry();geo.setAttribute('position',new T.Float32BufferAttribute(pts,3));geo.setAttribute('uv',new T.Float32BufferAttribute(uv,2));geo.setIndex(indices);geo.computeVertexNormals();return this.mesh(parent,geo,mat,p);}
 plate(parent:T.Object3D,points:[number,number][],depth:number,mat:Mat,p:V=[0,0,0],rotation:V=[0,0,0]){const shape=new T.Shape();points.forEach(([x,y],i)=>i?shape.lineTo(x,y):shape.moveTo(x,y));shape.closePath();const g=new T.ExtrudeGeometry(shape,{depth,bevelEnabled:true,bevelSegments:1,steps:1,bevelSize:.015,bevelThickness:.015});g.translate(0,0,-depth/2);return this.mesh(parent,g,mat,p,rotation);}
 tube(parent:T.Object3D,points:V[],radius:number,mat:Mat,taper=1){const curve=new T.CatmullRomCurve3(points.map(p=>new T.Vector3(...p)));const steps=Math.max(6,points.length*3),g=new T.TubeGeometry(curve,steps,radius,6,false);if(taper!==1){const pos=g.getAttribute('position');for(let i=0;i<=steps;i++){const center=curve.getPointAt(i/steps),s=1-(1-taper)*i/steps;for(let j=0;j<=6;j++){const k=i*7+j,v=new T.Vector3().fromBufferAttribute(pos,k).sub(center).multiplyScalar(s).add(center);pos.setXYZ(k,v.x,v.y,v.z);}}g.computeVertexNormals();}return this.mesh(parent,g,mat);}
 ring(parent:T.Object3D,radius:number,width:number,mat:Mat,p:V,rotation:V=[0,0,0]){return this.mesh(parent,new T.TorusGeometry(radius,width,6,24),mat,p,rotation);}
 group(parent:T.Object3D,name:string,p:V=[0,0,0]){const g=new T.Group();g.name=name;g.position.set(...p);parent.add(g);return g;}
 strap(parent:T.Object3D,a:V,b:V,width:number,mat:Mat){const start=new T.Vector3(...a),end=new T.Vector3(...b),m=this.round(parent,[width,start.distanceTo(end),.035],mat,start.clone().add(end).multiplyScalar(.5).toArray() as V,undefined,.012);m.quaternion.setFromUnitVectors(new T.Vector3(0,1,0),end.sub(start).normalize());return m;}
 cloth(parent:T.Object3D,name:string,width:number,length:number,mat:Mat,p:V,angle=0,pointed=false){const g=this.group(parent,name,p);g.rotation.z=angle;const shape=pointed?[[-width*.5,0],[width*.5,0],[width*.34,-length*.68],[0,-length],[-width*.4,-length*.72]]:[[-width*.5,0],[width*.5,0],[width*.46,-length*.89],[width*.12,-length],[-width*.12,-length*.82],[-width*.5,-length*.94]];const m=this.plate(g,shape as [number,number][],.018,mat);const pos=m.geometry.getAttribute('position');for(let i=0;i<pos.count;i++)pos.setZ(i,pos.getZ(i)-Math.pow(Math.max(0,-pos.getY(i))/length,2)*.18);m.geometry.computeVertexNormals();return g;}
 decal(parent:T.Object3D,text:string,color:string,w:number,h:number,p:V,back=false){if(typeof document==='undefined')return;const c=document.createElement('canvas');c.width=512;c.height=256;const ctx=c.getContext('2d')!;ctx.fillStyle=color;ctx.textAlign='center';const lines=text.split('\n');ctx.font=`700 ${lines.length>1?86:120}px Arial`;lines.forEach((line,i)=>ctx.fillText(line,256,lines.length>1?95+i*108:174));const texture=new T.CanvasTexture(c);texture.colorSpace=T.SRGBColorSpace;const m=new T.Mesh(new T.PlaneGeometry(w,h),new T.MeshStandardMaterial({map:texture,transparent:true,alphaTest:.15,roughness:.8,depthWrite:false}));m.position.set(...p);if(back)m.rotation.y=Math.PI;parent.add(m);}
 // Merge only within each attachment, preserving every animated parent and secondary pivot.
 batch(root:T.Object3D){root.traverse(parent=>{const byMat=new Map<T.Material,T.Mesh[]>();for(const o of [...parent.children])if(o instanceof T.Mesh&&!(o instanceof T.InstancedMesh)&&!Array.isArray(o.material)&&!o.material.transparent&&!o.userData.keep){const list=byMat.get(o.material)??[];list.push(o);byMat.set(o.material,list);}for(const [material,list] of byMat){if(list.length<2)continue;const geos=list.map(m=>{m.updateMatrix();let g=m.geometry.clone().applyMatrix4(m.matrix);if(g.index){const expanded=g.toNonIndexed();g.dispose();g=expanded;}for(const key of Object.keys(g.attributes))if(!['position','normal','uv'].includes(key))g.deleteAttribute(key);return g;});const merged=mergeGeometries(geos,false);geos.forEach(g=>g.dispose());if(!merged)continue;const mesh=new T.Mesh(merged,material);mesh.castShadow=mesh.receiveShadow=true;mesh.name='batched-details';parent.add(mesh);for(const m of list){parent.remove(m);m.geometry.dispose();}}});}
}
export function feature(root:T.Object3D,name:string){const list=root.userData.designFeatures??=[];list.push(name);root.userData.designFeatures=list;}


