import {test} from 'node:test';
import assert from 'node:assert/strict';
import type {WebSocket} from 'ws';
import {RoomServer} from '../server/rooms';
import {CHARACTER_IDS,SELECTION} from '../shared/characters';
import {MAPS} from '../shared/map';
import {isWalkable,freshMotion,advanceMotion,STEP} from '../shared/game';
import {ROUND} from '../shared/rounds';
function fixture(count=2){const server=new RoomServer(true),packets:any[][]=[];const sockets=Array.from({length:count},(_,i)=>({readyState:1,send:(s:string)=>{(packets[i]??=[]).push(JSON.parse(s));}} as unknown as WebSocket));const send=(i:number,m:any)=>server.message(sockets[i],JSON.stringify(m));send(0,{type:'create',name:'P0'});const room=server.sessions.get(sockets[0])!.room;for(let i=1;i<count;i++)send(i,{type:'join',code:room.code,name:'P'+i});const start=()=>{for(let i=0;i<count;i++)send(i,{type:'ready',ready:true});send(0,{type:'start'});};const choose=(i:number,id:string=CHARACTER_IDS[i%8])=>send(i,{type:'choose_character',matchId:room.match.id,characterId:id});const prepare=(i:number)=>send(i,{type:'character_prepared',matchId:room.match.id});return {server,room,sockets,send,start,choose,prepare,packets};}
test('host start freezes roster, opens server-timed selection, prevents gameplay and joining',()=>{const f=fixture();f.send(1,{type:'start'});assert.equal(f.room.phase,'lobby');f.send(0,{type:'start'});assert.equal(f.room.phase,'lobby');f.start();assert.equal(f.room.phase,'character_selection');assert.equal(f.room.match.roundNumber,0);assert.equal(f.room.round.endsAt,0);assert.equal(f.room.selection!.deadline-f.room.selection!.startedAt,30_000);assert.equal(f.room.selection!.expiresAt-f.room.selection!.startedAt,39_000);const before=f.room.players.map(p=>({...p}));f.send(0,{type:'input',matchId:f.room.match.id,roundNumber:0,seq:1,dx:1,dy:0});f.server.tick();assert.equal(f.room.players[0].x,before[0].x);const id=f.room.match.id;f.send(0,{type:'start'});assert.equal(f.room.match.id,id);});
test('invalid/stale equip rejected; duplicate choices allowed; first equip immutable; loading waits for every client',()=>{const f=fixture(6);f.start();f.choose(0,'fake');assert.equal(f.room.players[0].characterId,null);f.send(0,{type:'choose_character',matchId:'old',characterId:'kirin'});assert.equal(f.room.players[0].characterId,null);f.choose(0,'kirin');f.choose(0,'shade');assert.equal(f.room.players[0].characterId,'kirin');for(let i=1;i<6;i++)f.choose(i,'kirin');assert.equal(f.room.phase,'match_loading');assert.equal(f.room.match.roundNumber,0);for(let i=0;i<5;i++)f.prepare(i);assert.equal(f.room.phase,'match_loading');f.prepare(5);assert.equal(f.room.phase,'arena');assert.equal(f.room.match.roundNumber,1);f.prepare(5);f.send(0,{type:'start'});assert.equal(f.room.match.roundNumber,1);assert(f.room.players.every(p=>p.characterId==='kirin'));});
test('deadline assigns only valid server-random skins at exactly 30 seconds and cancels incomplete preparation at 39',()=>{const f=fixture(6);f.start();f.choose(0,'shade');f.server.tick(f.room.selection!.deadline-1);assert.equal(f.room.players[1].characterId,null);f.server.tick(f.room.selection!.deadline);assert.equal(f.room.phase,'match_loading');assert(f.room.players.every(p=>CHARACTER_IDS.includes(p.characterId!)));assert.equal(f.room.players[0].characterAutoAssigned,false);assert(f.room.players.slice(1).every(p=>p.characterAutoAssigned));const skins=f.room.players.map(p=>p.characterId);f.choose(1,'lumi');assert.deepEqual(f.room.players.map(p=>p.characterId),skins);f.server.tick(f.room.selection!.expiresAt);assert.equal(f.room.phase,'lobby');assert(f.room.players.every(p=>p.characterId===null&&!p.ready));});
test('selection, equipped identity and deadline recover on resume; host migration and permanent leave follow room rules',()=>{const f=fixture(3);f.start();f.choose(0,'gravel');const deadline=f.room.selection!.deadline,p=f.room.players[0],token=p.token;f.server.disconnect(f.sockets[0]);assert.equal(f.room.hostId,f.room.players[1].id);const out:any[]=[],socket={readyState:1,send:(s:string)=>out.push(JSON.parse(s))} as unknown as WebSocket;f.server.message(socket,JSON.stringify({type:'resume',code:f.room.code,token}));assert.equal(out[0].room.selection.deadline,deadline);assert.equal(out[0].room.players[0].characterId,'gravel');f.server.remove(f.room,f.room.players[2]);assert.equal(f.room.phase,'character_selection');f.server.remove(f.room,f.room.players[1]);assert.equal(f.room.phase,'lobby');});
test('all eight skins survive KO/respawn, all three maps, results and reset for a fresh match',()=>{for(const id of CHARACTER_IDS){const f=fixture();f.start();f.choose(0,id);f.choose(1,'shade');f.prepare(0);f.prepare(1);const match=f.room.match.id,p=f.room.players[0];p.health=0;p.koRemaining=STEP;f.server.tick();assert.equal(p.health,100);assert.equal(p.characterId,id);assert(isWalkable(p,MAPS[f.room.mapId]));for(let n=1;n<=3;n++){assert.equal(f.room.phase,'arena');assert.equal(p.characterId,id);assert.equal(f.room.match.id,match);f.server.tick(f.room.round.endsAt);if(n<3)f.server.tick(f.room.round.returnAt);}assert.equal(f.room.phase,'complete');assert.equal(p.characterId,id);f.send(0,{type:'lobby'});assert.equal(p.characterId,null);f.start();assert.equal(f.room.phase,'character_selection');assert.notEqual(f.room.match.id,match);}});
test('all upgraded map spawns, authored floor support and current jump/sprint/dash are compatible',()=>{assert.equal(Object.keys(MAPS).length,5);for(const map of Object.values(MAPS)){for(const spawn of map.spawns){assert(isWalkable(spawn,map),map.id+JSON.stringify(spawn));let p=freshMotion(spawn);p=advanceMotion(p,{dx:1,dy:0,sprint:true},STEP,map);assert(isWalkable(p,map));p=advanceMotion(p,{dx:0,dy:1,dashId:1},STEP,map);assert(isWalkable(p,map));p=advanceMotion(p,{dx:0,dy:0,jumpId:1},STEP,map);assert(p.airborne);for(let i=0;i<40;i++)p=advanceMotion(p,{dx:0,dy:0},STEP,map);assert(!p.airborne);assert(isWalkable(p,map));}}});
