import * as THREE from 'three';
import {test} from 'node:test';
import assert from 'node:assert/strict';
import type {WebSocket} from 'ws';
import {RoomServer} from '../server/rooms.js';
import {beginMode,interact,tickMode,throwBall,MODE_RULES} from '../server/modes.js';
import {CHEST_OPEN_MS,pickupPosition,interactionItem} from '../shared/loot.js';
import {MAPS} from '../shared/map.js';
import {RULES,type GameMode} from '../shared/modes.js';
import {isWalkable,STEP} from '../shared/game.js';
import {createItemArt,revealPosition} from '../src/ItemArt';
function fixture(mode:GameMode='tag'){
 const server=new RoomServer(),packets:any[][]=[];const sockets=Array.from({length:2},()=>{const output:any[]=[];packets.push(output);return {readyState:1,send:(raw:string)=>output.push(JSON.parse(raw))} as unknown as WebSocket;});
 const send=(i:number,m:any)=>server.message(sockets[i],JSON.stringify(m));send(0,{type:'create',name:'Host'});const room=server.sessions.get(sockets[0])!.room;send(1,{type:'join',name:'Guest',code:room.code});send(0,{type:'settings',mode,format:'solo'});send(0,{type:'ready',ready:true});send(1,{type:'ready',ready:true});send(0,{type:'start'});return {server,room,send,packets};
}
for(const mode of ['tag','kill_race','flag_run'] as const)test(`${mode}: chest opening is timed, shared, exclusive and uses the existing pickup`,()=>{
 const f=fixture(mode),now=Date.now(),chest=f.room.mode.items.find(i=>i.source==='chest')!;f.room.players.forEach(p=>Object.assign(p,{x:chest.x,y:chest.y,elevation:chest.elevation??0}));
 interact(f.room,f.room.players[0],now);const kind=chest.kind;assert.equal(chest.state,'opening');assert(MODE_RULES[mode].loot.includes(kind!));assert(f.room.players.every(p=>p.heldItem===null));interact(f.room,f.room.players[1],now+20);assert.equal(chest.kind,kind);assert.equal(chest.openedAt,now);
 tickMode(f.room,now+CHEST_OPEN_MS-1,STEP);assert.equal(chest.state,'opening');tickMode(f.room,now+CHEST_OPEN_MS,STEP);assert.equal(chest.state,'opened');f.server.broadcast(f.room);assert(f.packets.every(messages=>messages.at(-1).room.mode.items.find((i:any)=>i.id===chest.id).state==='opened'));
 f.room.players.forEach(p=>Object.assign(p,{...pickupPosition(chest),elevation:pickupPosition(chest).elevation??0}));interact(f.room,f.room.players[0],now+CHEST_OPEN_MS);interact(f.room,f.room.players[1],now+CHEST_OPEN_MS);assert.equal(chest.state,'empty');assert.equal(f.room.players[0].heldItem,kind);assert.equal(f.room.players[1].heldItem,null);tickMode(f.room,now+30000,STEP);assert.equal(chest.state,'empty');assert.equal(chest.openedAt,now);
});
test('all maps use designated chests with supported reachable loot positions, separate from floor pickups',()=>{
 const f=fixture();for(const mapId of Object.keys(MAPS)){f.room.mapId=mapId;beginMode(f.room,1000);for(const chest of f.room.mode.items.filter(i=>i.source==='chest')){const p=f.room.players[0];Object.assign(p,{x:chest.x,y:chest.y,elevation:chest.elevation??0});interact(f.room,p,1000);assert.equal(chest.state,'opening');const drop=pickupPosition(chest);assert(isWalkable(drop,MAPS[mapId]),mapId);assert(Math.hypot(drop.x-chest.x,drop.y-chest.y)<=28);tickMode(f.room,1000+CHEST_OPEN_MS,STEP);Object.assign(p,{...drop,elevation:drop.elevation??0});assert.equal(interactionItem(f.room.mode.items,mapId,p)?.id,chest.id);interact(f.room,p,1500);assert.equal(p.heldItem,'freeze_ball');p.heldItem=null;}
 const floor=f.room.mode.items.find(i=>i.source==='floor')!;assert.equal(floor.state,'opened');Object.assign(f.room.players[0],{x:floor.x,y:floor.y,elevation:floor.elevation??0});interact(f.room,f.room.players[0],2000);assert.equal(floor.state,'empty');assert.equal(floor.openedAt,undefined);tickMode(f.room,2000+RULES.itemRespawnMs,STEP);assert.equal(floor.state,'opened');}
});
test('out of range, frozen, KO and disconnected players cannot open chests',()=>{const f=fixture(),p=f.room.players[0],chest=f.room.mode.items.find(i=>i.source==='chest')!;p.x=chest.x+500;p.y=chest.y;interact(f.room,p,1000);assert.equal(chest.state,'closed');Object.assign(p,{x:chest.x,y:chest.y,elevation:chest.elevation??0});p.frozenUntil=2000;interact(f.room,p,1000);assert.equal(chest.state,'closed');p.frozenUntil=0;p.health=0;interact(f.room,p,1000);assert.equal(chest.state,'closed');p.health=100;p.socket=null;interact(f.room,p,1000);assert.equal(chest.state,'closed');});
test('Freeze Ball preserves speed, lifetime and freeze duration with bounded authoritative effects',()=>{const f=fixture(),[p,q]=f.room.players;Object.assign(p,{x:1000,y:700,elevation:0,heldItem:'freeze_ball',attackX:1,attackY:0});Object.assign(q,{x:1080,y:700,elevation:0});throwBall(f.room,p,1000);assert.equal(p.heldItem,null);assert.equal(f.room.mode.projectiles[0].expiresAt,1000+RULES.ballLifetimeMs);assert.equal(f.room.mode.effects[0].type,'throw');tickMode(f.room,1033,STEP);assert(Math.abs(f.room.mode.projectiles[0].x-(1000+RULES.ballSpeed*STEP))<1e-6);for(let i=2;i<=5;i++)tickMode(f.room,1000+i*33,STEP);const hit=f.room.mode.effects.find(e=>e.type==='ice_hit')!;assert(hit);assert.equal(hit.targetId,q.id);assert.equal(q.frozenUntil,hit.at+3000);tickMode(f.room,5000,STEP);assert.equal(f.room.mode.effects.length,0);});
test('reusable chest uses hinge rotation, stays open when looted, and art resources are shared',()=>{const resources=new Set<any>(),track=<T extends {dispose:()=>void}>(r:T):T=>{resources.add(r);return r;},art=createItemArt(track),a=art.chest(),b=art.chest();const chest:any={x:100,y:100,id:'chest',source:'chest',kind:null,state:'closed',refreshAt:0};a.update(chest,1000);assert.equal(a.hinge.rotation.x,0);const hingePosition=a.hinge.position.clone();Object.assign(chest,{state:'opening',openedAt:1000});a.update(chest,1210);assert(a.hinge.rotation.x<0&&a.hinge.rotation.x>-1.85);assert(a.hinge.position.equals(hingePosition));chest.state='empty';a.update(chest,1800);assert.equal(a.hinge.rotation.x,-1.85);assert.equal(a.interior.material.opacity,.85);const count=resources.size;for(let i=0;i<100;i++)art.freezeBall();assert.equal(resources.size,count);assert.equal(a.group.name,'GAMEPLAY_LOOT_CHEST');assert.equal(b.group.name,a.group.name);const drop=revealPosition({...chest,pickupPosition:{x:120,y:100}},1800);assert.equal(drop.x,120*.03);for(const kind of ['blade','hammer','freeze_ball']){const model=art.item(kind);model.position.copy(revealPosition({...chest,kind},1800));model.updateMatrixWorld(true);assert(new THREE.Box3().setFromObject(model).min.y>=0,`${kind} stays above its supported floor`);}for(const r of resources)r.dispose();});
import {createLootEffects} from '../src/LootEffects';
test('ice bursts are pooled, include an immediate flash and stop rendering after expiry',()=>{
 const previous=(globalThis as any).window;(globalThis as any).window={addEventListener(){},removeEventListener(){}};
 const resources=new Set<any>(),track=<T extends {dispose:()=>void}>(r:T):T=>{resources.add(r);return r;},scene=new THREE.Scene();let effects:ReturnType<typeof createLootEffects>|undefined;
 try{effects=createLootEffects(scene,track);const count=resources.size,children=scene.children.length;const room:any={serverTime:1000,mode:{projectiles:[],effects:[{id:'hit',type:'ice_hit',at:1000,ownerId:'a',targetId:'b',x:100,y:100,dx:1,dy:0}]}};effects.updateProjectiles(room,1000,()=>undefined);const burst=scene.children.find(g=>g.visible&&g.children.length===11)!;assert(burst);assert(burst.children.at(-1)!.visible);effects.updateProjectiles(room,1200,()=>undefined);assert.equal(burst.children.at(-1)!.visible,false);for(let i=0;i<100;i++){room.mode.effects=[{...room.mode.effects[0],id:`hit-${i}`,at:2000+i*10}];effects.updateProjectiles(room,2000+i*10,()=>undefined);}assert.equal(resources.size,count);assert.equal(scene.children.length,children);room.mode.effects=[];effects.updateProjectiles(room,5000,()=>undefined);assert(scene.children.every(g=>!g.visible));
 }finally{effects?.dispose();for(const r of resources)r.dispose();(globalThis as any).window=previous;}
});
