import {test} from 'node:test';
import assert from 'node:assert/strict';
import {MAPS,mapEnvironment} from '../shared/map';
import {selectRoundMap,selectMapVariant} from '../shared/map-rotation';
import {freshMotion,advanceMotion,isWalkable,STEP} from '../shared/game';
import {TRAVERSAL} from '../shared/traversal';
import {canHit,safeSpawn} from '../shared/combat';
const map=MAPS.outlaws_canyon;
function travel(start:{x:number;y:number;elevation?:number},points:number[][]){let p=freshMotion(start);for(const [x,y,e] of points){for(let i=0;i<1600&&Math.hypot(x-p.x,y-p.y)>5;i++){const dx=x-p.x,dy=y-p.y,l=Math.hypot(dx,dy);p=advanceMotion(p,{dx:dx/l,dy:dy/l,sprint:true},STEP,map);assert(isWalkable(p,map));}assert(Math.hypot(x-p.x,y-p.y)<7,`Blocked ${p.x.toFixed(1)},${p.y.toFixed(1)},${p.elevation.toFixed(1)} toward ${x},${y}`);if(e!==undefined)assert(Math.abs(p.elevation-e)<2,`Height ${p.elevation} expected ${e} at ${x},${y}`);}return p;}
test('four registered maps preserve opening/no-repeat selection; Outlaw has no Aerie variant',()=>{assert.equal(selectRoundMap(1,map.id,()=>0),'central_plaza');assert.equal(selectRoundMap(2,'central_plaza',()=>2),map.id);assert.equal(selectMapVariant(map.id,()=>{throw Error('Should not randomize')}),null);assert.equal(mapEnvironment(map,'night'),map.environment);assert.equal(selectMapVariant('aerie_sky_port',()=>1),'night');});
test('eight canyon spawns are valid, spread and all ramps fit the unchanged slope limit',()=>{assert.equal(map.spawns.length,8);for(const p of map.spawns)assert(isWalkable(p,map),JSON.stringify(p));for(let i=0;i<8;i++)for(let j=i+1;j<8;j++)assert(Math.hypot(map.spawns[i].x-map.spawns[j].x,map.spawns[i].y-map.spawns[j].y)>250);for(const s of map.surfaces)if(s.ramp)assert(Math.abs(s.ramp.to-s.ramp.from)/(s.ramp.axis==='x'?s.width:s.height)<=TRAVERSAL.maxSlope);assert(isWalkable(safeSpawn([],map),map));});
test('town street connects Dust-Up Plaza to crossing with clear alternative alleys',()=>{travel({x:950,y:380},[[950,700,0],[1080,1000,0],[1160,1360,0],[1120,1510,0],[1130,1900,0],[980,2120,0],[1120,2170,0],[1120,2420,0]]);travel({x:260,y:1370},[[260,1430,0],[600,1430,0],[640,1980,0],[550,2380,0]]);travel({x:1650,y:1250},[[1660,1310,0],[1720,1310,0]]);});
test('saloon porch climbs to rooftop, crosses upper bridge and descends eastern stairs',()=>{travel({x:1080,y:900},[[800,900,80],[790,810,80],[790,750,92.5],[790,450,160],[1000,430,160],[1230,430,160],[1230,330,160],[1550,330,160],[1550,850,0]]);});
test('two Renegade approaches and bridge connect both outposts and mine overlook',()=>{travel({x:470,y:2120},[[470,1820,80],[470,1660,80],[270,1660,80],[470,1660,80],[1100,1660,80],[1200,1660,80],[1300,1700,80],[1460,1700,80],[1460,1580,80],[1460,1700,80],[1650,1710,80],[1650,1370,0]]);travel({x:470,y:1400,elevation:80},[[470,1280,80],[260,1280,80],[470,1280,80],[470,1000,80],[600,900,80]]);});
test('dash cannot escape canyon ground or clip buildings; low/upper melee respects solid architecture',()=>{let p=freshMotion({x:580,y:390});for(let i=0;i<100;i++)p=advanceMotion(p,{dx:-1,dy:0,dashId:1},STEP,map);assert(isWalkable(p,map));assert(p.x>=300+TRAVERSAL.radius);assert(!isWalkable({x:550,y:650,elevation:0},map));assert(canHit({x:950,y:1180,elevation:0},{x:990,y:1180,elevation:0},1,0,map));assert(!canHit({x:550,y:650,elevation:80},{x:550,y:650,elevation:160},1,0,map));});
import {RoomServer} from '../server/rooms';
import type {WebSocket} from 'ws';
test('Aerie night to Canyon clears variant, restores reconnect state and finishes fresh matches for two/six players',()=>{for(const count of [2,6]){
 const server=new RoomServer(),socket=()=>({readyState:1,send:()=>{}} as unknown as WebSocket),sockets=Array.from({length:count},socket);server.message(sockets[0],JSON.stringify({type:'create',name:'A'}));const room=server.sessions.get(sockets[0])!.room;
 for(let i=1;i<count;i++)server.message(sockets[i],JSON.stringify({type:'join',name:`P${i}`,code:room.code}));for(const ws of sockets)server.message(ws,JSON.stringify({type:'ready',ready:true}));server.message(sockets[0],JSON.stringify({type:'start'}));assert.equal(room.mapId,'central_plaza');assert.equal(room.match.totalRounds,3);
 server.tick(room.round.endsAt);room.nextMapId='aerie_sky_port';room.nextMapVariant='night';server.tick(room.round.returnAt);assert.equal(room.mapVariant,'night');server.tick(room.round.endsAt);room.nextMapId=map.id;room.nextMapVariant=selectMapVariant(map.id,()=>0);server.tick(room.round.returnAt);assert.equal(room.mapVariant,null);assert.equal(room.mapId,map.id);
 for(const [i,p] of room.players.entries()){assert.equal(p.x,map.spawns[i].x);assert.equal(p.y,map.spawns[i].y);assert(isWalkable(p,map));assert.equal(p.health,100);assert(p.targetId&&p.targetId!==p.id);assert.equal(server.view(room,p).mapId,map.id);assert.equal(server.view(room,p).mapVariant,null);}
 const p=room.players[0];p.matchEliminations=3;p.eliminations=1;p.health=75;const target=p.targetId;server.disconnect(sockets[0]);const replacement=socket();server.message(replacement,JSON.stringify({type:'resume',code:room.code,token:p.token}));assert.equal(room.players.length,count);assert.equal(server.view(room,p).mapVariant,null);assert.equal(p.matchEliminations,3);assert.equal(p.health,75);assert.equal(p.targetId,target);
 server.message(replacement,JSON.stringify({type:'input',matchId:room.match.id,roundNumber:3,seq:p.seq+1,dx:0,dy:0,mapId:'aerie_sky_port',mapVariant:'night'}));assert.equal(room.mapId,map.id);assert.equal(room.mapVariant,null);server.tick(room.round.endsAt);assert.equal(room.phase,'complete');assert.equal(room.match.results[0].eliminations,3);
 const host=room.players.find(p=>p.id===room.hostId)!;server.message(host.socket!,JSON.stringify({type:'lobby'}));for(const p of room.players)server.message(p.socket!,JSON.stringify({type:'ready',ready:true}));server.message(host.socket!,JSON.stringify({type:'start'}));assert.equal(room.mapId,'central_plaza');assert.equal(room.match.roundNumber,1);assert(room.players.every(p=>p.matchEliminations===0));
 }});
test('Canyon lethal Bounty attack credits once and respawn uses only safe Canyon coordinates',()=>{const server=new RoomServer(),socket=()=>({readyState:1,send:()=>{}} as unknown as WebSocket),a=socket(),b=socket();server.message(a,JSON.stringify({type:'create',name:'A'}));const room=server.sessions.get(a)!.room;server.message(b,JSON.stringify({type:'join',name:'B',code:room.code}));for(const ws of [a,b])server.message(ws,JSON.stringify({type:'ready',ready:true}));server.message(a,JSON.stringify({type:'start'}));server.tick(room.round.endsAt);room.nextMapId=map.id;room.nextMapVariant=null;server.tick(room.round.returnAt);room.round.endsAt=Date.now()+90000;const attacker=room.players[0],victim=room.players[1];Object.assign(attacker,{x:950,y:1180,elevation:0,protection:0,attackCooldown:0});Object.assign(victim,{x:990,y:1180,elevation:0,protection:0,health:25});server.message(a,JSON.stringify({type:'input',matchId:room.match.id,roundNumber:2,seq:attacker.seq+1,dx:0,dy:0,aimX:1,aimY:0,attackId:attacker.attackId+1}));let now=Date.now();server.tick(now);assert.equal(victim.health,0);assert.equal(attacker.eliminations,1);assert.equal(attacker.matchEliminations,1);for(let i=0;i<155;i++){now+=STEP*1000;server.tick(now);}assert.equal(victim.health,100);assert(victim.protection>0);assert(isWalkable(victim,map));assert(map.spawns.some(s=>s.x===victim.x&&s.y===victim.y));assert.equal(attacker.matchEliminations,1);});
test('upper Renegade bridge permits same-level melee but rejects attacks across floors',()=>{assert(isWalkable({x:1000,y:1660,elevation:80},map));assert(isWalkable({x:1040,y:1660,elevation:80},map));assert(canHit({x:1000,y:1660,elevation:80},{x:1040,y:1660,elevation:80},1,0,map));assert(!canHit({x:1000,y:1660,elevation:0},{x:1040,y:1660,elevation:80},1,0,map));});
