import {test} from 'node:test';
import assert from 'node:assert/strict';
import {MAPS,mapEnvironment} from '../shared/map';
import {selectRoundMap,selectMapVariant} from '../shared/map-rotation';
import {freshMotion,advanceMotion,isWalkable,STEP} from '../shared/game';
import {TRAVERSAL} from '../shared/traversal';
import {canHit,safeSpawn} from '../shared/combat';
import {RoomServer} from '../server/rooms';
import type {WebSocket} from 'ws';
const map=MAPS.vikings_fjord;
function travel(start:{x:number;y:number;elevation?:number},points:number[][]){let p=freshMotion(start);for(const [x,y,e] of points){for(let i=0;i<1600&&Math.hypot(x-p.x,y-p.y)>5;i++){const dx=x-p.x,dy=y-p.y,l=Math.hypot(dx,dy);p=advanceMotion(p,{dx:dx/l,dy:dy/l,sprint:true},STEP,map);assert(isWalkable(p,map),JSON.stringify(p));}assert(Math.hypot(x-p.x,y-p.y)<7,`Blocked ${p.x.toFixed(1)},${p.y.toFixed(1)},${p.elevation.toFixed(1)} toward ${x},${y}`);if(e!==undefined)assert(Math.abs(p.elevation-e)<2,`Height ${p.elevation} expected ${e}`);}return p;}
test('fifth arena participates in existing no-repeat rotation, never inherits Aerie variants',()=>{assert.equal(Object.keys(MAPS).length,5);assert.equal(selectRoundMap(1,map.id,()=>3),'central_plaza');assert.equal(selectRoundMap(2,'central_plaza',()=>3),map.id);assert.notEqual(selectRoundMap(3,map.id,()=>3),map.id);assert.equal(selectMapVariant(map.id,()=>{throw Error('No variants')}),null);assert.equal(mapEnvironment(map,'night'),map.environment);assert.equal(map.environment.theme,'fjord');});
test('eight Fjord spawns have valid support and separation; stairs meet existing slope limits',()=>{assert.equal(map.spawns.length,8);for(const p of map.spawns)assert(isWalkable(p,map),JSON.stringify(p));for(let i=0;i<8;i++)for(let j=i+1;j<8;j++)assert(Math.hypot(map.spawns[i].x-map.spawns[j].x,map.spawns[i].y-map.spawns[j].y)>250);for(const s of map.surfaces)if(s.ramp)assert(Math.abs(s.ramp.to-s.ramp.from)/(s.ramp.axis==='x'?s.width:s.height)<=TRAVERSAL.maxSlope);assert(isWalkable(safeSpawn([],map),map));});
test('Valhalla stairs and three-height fortress circuit have independent ascent and descent',()=>{travel({x:1030,y:1130},[[1030,800,90],[1160,730,90],[1360,730,90],[1360,650,90],[1360,330,180],[1360,250,180],[1080,290,180],[680,290,180],[680,650,90],[680,730,90],[470,750,90],[470,1200,90],[470,1560,0]]);});
test('Armory platform connects by south and west stairs without requiring new movement mechanics',()=>{travel({x:1720,y:1520},[[1720,1220,83.33],[1640,1220,83.33],[1640,1180,90],[1530,1180,90],[1530,1160,90],[1180,1160,0]]);});
test('short Raider cave flank reconnects into the crossing, Runestone Plaza and dock loop',()=>{travel({x:1560,y:1310},[[1560,1700,0],[1400,1700,0],[1400,1780,0],[1410,1800,0],[1410,2080,80],[1180,2170,80],[810,2170,80],[810,1780,0],[880,1750,0],[880,1510,0],[1140,1510,0]]);});
test('frozen crossings keep ordinary walking, sprint, stamina and dash behavior',()=>{let walk=freshMotion({x:950,y:1390}),sprint=freshMotion({x:950,y:1390}),dash=freshMotion({x:950,y:1390});for(let i=0;i<10;i++){walk=advanceMotion(walk,{dx:0,dy:1},STEP,map);sprint=advanceMotion(sprint,{dx:0,dy:1,sprint:true},STEP,map);dash=advanceMotion(dash,{dx:0,dy:1,dashId:1},STEP,map);}assert(Math.abs(walk.y-1390-220*STEP*10)<.01);assert(Math.abs(sprint.y-1390-330*STEP*10)<.01);assert(sprint.stamina<100);assert(dash.y>sprint.y&&dash.dashCooldown>0);assert(isWalkable(dash,map));});
test('Fjord geometry blocks dash escapes, longhouses and melee through raised floors',()=>{let p=freshMotion({x:480,y:1930});for(let i=0;i<100;i++)p=advanceMotion(p,{dx:-1,dy:0,dashId:1},STEP,map);assert(isWalkable(p,map));assert(p.x>=400+TRAVERSAL.radius);assert(!isWalkable({x:1030,y:500},map));assert(canHit({x:950,y:1390},{x:990,y:1390},1,0,map));assert(canHit({x:1100,y:2170,elevation:80},{x:1140,y:2170,elevation:80},1,0,map));assert(!canHit({x:1100,y:2170,elevation:0},{x:1140,y:2170,elevation:80},1,0,map));assert(!canHit({x:1400,y:1490},{x:1440,y:1490},1,0,map));});
function fixture(count=2){const server=new RoomServer(),socket=()=>({readyState:1,send:()=>{}} as unknown as WebSocket),sockets=Array.from({length:count},socket);server.message(sockets[0],JSON.stringify({type:'create',name:'A'}));const room=server.sessions.get(sockets[0])!.room;for(let i=1;i<count;i++)server.message(sockets[i],JSON.stringify({type:'join',name:`P${i}`,code:room.code}));for(const ws of sockets)server.message(ws,JSON.stringify({type:'ready',ready:true}));server.message(sockets[0],JSON.stringify({type:'start'}));return {server,sockets,room,socket};}
test('two/six players transition Aerie night → Fjord, resume current state and reset to Central Plaza',()=>{for(const count of [2,6]){const {server,sockets,room,socket}=fixture(count);assert.equal(room.mapId,'central_plaza');assert.equal(room.match.totalRounds,3);server.tick(room.round.endsAt);room.nextMapId='aerie_sky_port';room.nextMapVariant='night';server.tick(room.round.returnAt);server.tick(room.round.endsAt);room.nextMapId=map.id;room.nextMapVariant=selectMapVariant(map.id,()=>0);server.tick(room.round.returnAt);assert.equal(room.mapVariant,null);for(const [i,p] of room.players.entries()){assert.equal(p.x,map.spawns[i].x);assert.equal(p.y,map.spawns[i].y);assert.equal(p.elevation,map.spawns[i].elevation??0);assert(isWalkable(p,map));assert.equal(p.health,100);assert(p.targetId&&p.targetId!==p.id);assert.equal(server.view(room,p).mapId,map.id);}const p=room.players[0];p.health=75;p.matchEliminations=3;const target=p.targetId;server.disconnect(sockets[0]);const resumed=socket();server.message(resumed,JSON.stringify({type:'resume',code:room.code,token:p.token}));assert.equal(room.players.length,count);assert.equal(server.view(room,p).mapId,map.id);assert.equal(server.view(room,p).mapVariant,null);assert.equal(p.health,75);assert.equal(p.targetId,target);server.tick(room.round.endsAt);assert.equal(room.phase,'complete');assert.equal(room.match.results[0].eliminations,3);const host=room.players.find(p=>p.id===room.hostId)!;server.message(host.socket!,JSON.stringify({type:'lobby'}));for(const q of room.players)server.message(q.socket!,JSON.stringify({type:'ready',ready:true}));server.message(host.socket!,JSON.stringify({type:'start'}));assert.equal(room.mapId,'central_plaza');assert.equal(room.match.roundNumber,1);assert(room.players.every(q=>q.matchEliminations===0));}});
test('Fjord lethal Bounty attack scores once and respawn restores map-specific safe spawn/protection',()=>{const {server,sockets,room}=fixture();server.tick(room.round.endsAt);room.nextMapId=map.id;room.nextMapVariant=null;server.tick(room.round.returnAt);room.round.endsAt=Date.now()+90000;const attacker=room.players[0],victim=room.players[1];Object.assign(attacker,{x:950,y:1390,elevation:0,protection:0,attackCooldown:0});Object.assign(victim,{x:990,y:1390,elevation:0,protection:0,health:25});server.message(sockets[0],JSON.stringify({type:'input',matchId:room.match.id,roundNumber:2,seq:attacker.seq+1,dx:0,dy:0,aimX:1,aimY:0,attackId:attacker.attackId+1}));let now=Date.now();server.tick(now);assert.equal(victim.health,0);assert.equal(attacker.eliminations,1);assert.equal(attacker.matchEliminations,1);for(let i=0;i<155;i++){now+=STEP*1000;server.tick(now);}assert.equal(victim.health,100);assert(victim.protection>0);assert(isWalkable(victim,map));assert(map.spawns.some(s=>s.x===victim.x&&s.y===victim.y));});
test('outer fortress spawns have usable ground/raised exits to the southern basin',()=>{travel(map.spawns[0],[[1500,150,0],[1500,820,0],[1530,1090,0],[1560,1310,0],[1560,1700,0],[1400,1780,0]]);travel(map.spawns[1],[[1450,1090,0],[1530,1090,0],[1560,1310,0],[1560,1700,0]]);travel(map.spawns[2],[[270,1550,0],[550,1550,0],[650,1550,0],[650,1650,0],[880,1750,0]]);});
test('dash uses the same support/collision on stairs, battlements and dock bridges',()=>{for(const [start,dx,dy] of [[{x:1030,y:1100},0,-1],[{x:1360,y:650,elevation:90},0,-1],[{x:1200,y:2170,elevation:80},1,0]] as const){let p=freshMotion(start);for(let i=0;i<15;i++){p=advanceMotion(p,{dx,dy,dashId:1},STEP,map);assert(isWalkable(p,map));}assert(p.dashCooldown>0);assert(Math.hypot(p.x-start.x,p.y-start.y)>50);}});
