import * as T from 'three';
import type {MapBlock,Surface} from '../../shared/maps/types';
import {surfaceHeight} from '../../shared/traversal';
import {VIEW} from '../../shared/presentation';
/** Static district geometry is pooled by primitive/material. Collision proxies remain separate. */
export class PlazaKit{
 readonly root=new T.Group();readonly solids:T.Object3D[]=[];private resources=new Set<{dispose:()=>void}>();private materials=new Map<string,T.Material>();private textures=new Map<string,T.Texture>();private batches=new Map<string,{geometry:T.BufferGeometry;material:T.Material;matrices:T.Matrix4[]}>();
 readonly cube=this.track(new T.BoxGeometry(1,1,1));readonly plane=this.track(new T.PlaneGeometry(1,1));readonly cylinder=this.track(new T.CylinderGeometry(.5,.5,1,12));readonly sphere=this.track(new T.IcosahedronGeometry(.5,1));readonly hidden=this.track(new T.MeshBasicMaterial({visible:false}));
 constructor(public scene:T.Scene){this.root.name='central-plaza-environment';scene.add(this.root);}
 track<R extends {dispose:()=>void}>(resource:R):R{this.resources.add(resource);return resource;}
 material(color:string,kind:'concrete'|'brick'|'metal'|'wet'|'glass'|'glow'|'wood'='concrete'){
  const key=color+kind;let mat=this.materials.get(key);if(mat)return mat;
  if(kind==='glow')mat=this.track(new T.MeshBasicMaterial({color,toneMapped:false}));
  else{const roughness={concrete:.84,brick:.9,metal:.44,wet:.23,glass:.18,wood:.84}[kind];const texture=['concrete','brick','wet','wood'].includes(kind)?this.texture(kind):undefined;mat=this.track(new T.MeshStandardMaterial({color,roughness,metalness:kind==='metal'?.65:kind==='wet'?.38:kind==='glass'?.55:.05,...(texture?{map:texture,bumpMap:texture}:{}),bumpScale:kind==='brick'?.045:.014}));}
  this.materials.set(key,mat);return mat;
 }
 texture(kind:string){let texture=this.textures.get(kind);if(texture)return texture;const c=document.createElement('canvas');c.width=c.height=128;const g=c.getContext('2d')!;g.fillStyle='#d6d6d6';g.fillRect(0,0,128,128);for(let i=0;i<1300;i++){const v=174+(i*37%64);g.fillStyle=`rgb(${v},${v},${v})`;g.fillRect(i*53%128,i*79%128,1+i%3,1);}if(kind==='brick'){g.strokeStyle='#797979';g.lineWidth=2;for(let y=0;y<128;y+=16){g.beginPath();g.moveTo(0,y);g.lineTo(128,y);g.stroke();for(let x=(y/16%2)*16;x<128;x+=32){g.beginPath();g.moveTo(x,y);g.lineTo(x,y+16);g.stroke();}}}if(kind==='wet'){g.strokeStyle='#999999';g.lineWidth=1;g.strokeRect(0,0,128,128);}texture=this.track(new T.CanvasTexture(c));texture.wrapS=texture.wrapT=T.RepeatWrapping;texture.colorSpace=T.SRGBColorSpace;this.textures.set(kind,texture);return texture;}
 add(geometry:T.BufferGeometry,material:T.Material,p:[number,number,number],scale:[number,number,number],rotation:[number,number,number]=[0,0,0]){const object=new T.Object3D();object.position.set(...p.map(n=>n*VIEW.scale) as [number,number,number]);object.scale.set(...scale.map(n=>n*VIEW.scale) as [number,number,number]);object.rotation.set(...rotation);object.updateMatrix();const key=geometry.uuid+material.uuid;const batch=this.batches.get(key)??{geometry,material,matrices:[]};batch.matrices.push(object.matrix.clone());this.batches.set(key,batch);return object;}
 box(x:number,y:number,w:number,d:number,bottom:number,height:number,mat:T.Material){return this.add(this.cube,mat,[x+w/2,bottom+height/2,y+d/2],[w,height,d]);}
 cylinderAt(x:number,y:number,radius:number,bottom:number,height:number,mat:T.Material){return this.add(this.cylinder,mat,[x,bottom+height/2,y],[radius*2,height,radius*2]);}
 beam(a:[number,number,number],b:[number,number,number],width:number,mat:T.Material){const start=new T.Vector3(...a),end=new T.Vector3(...b),object=new T.Object3D();object.position.copy(start.clone().add(end).multiplyScalar(.5*VIEW.scale));object.scale.set(width*VIEW.scale,start.distanceTo(end)*VIEW.scale,width*VIEW.scale);object.quaternion.setFromUnitVectors(new T.Vector3(0,1,0),end.sub(start).normalize());object.updateMatrix();const key=this.cube.uuid+mat.uuid,batch=this.batches.get(key)??{geometry:this.cube,material:mat,matrices:[]};batch.matrices.push(object.matrix.clone());this.batches.set(key,batch);}
 sign(text:string,x:number,y:number,elevation:number,width:number,color:string,yaw=0){const key='sign:'+text+color;let texture=this.textures.get(key);if(!texture){const c=document.createElement('canvas');c.width=512;c.height=128;const g=c.getContext('2d')!;g.fillStyle='#081522';g.fillRect(0,0,512,128);g.strokeStyle=color;g.lineWidth=4;g.strokeRect(4,4,504,120);g.textAlign='center';g.font=`700 ${text.length>18?24:text.length>11?32:48}px Arial`;g.fillStyle=color;g.fillText(text,256,76);g.fillRect(120,101,272,3);texture=this.track(new T.CanvasTexture(c));texture.colorSpace=T.SRGBColorSpace;this.textures.set(key,texture);}const material=this.track(new T.MeshBasicMaterial({map:texture,side:T.DoubleSide,toneMapped:false}));const mesh=new T.Mesh(this.plane,material);mesh.position.set(x*VIEW.scale,elevation*VIEW.scale,y*VIEW.scale);mesh.scale.set(width*VIEW.scale,width*.25*VIEW.scale,1);mesh.rotation.y=yaw;this.root.add(mesh);}
 solid(b:MapBlock){const geo=b.shape==='ellipse'?this.cylinder:this.cube,mesh=new T.Mesh(geo,this.hidden);mesh.position.set((b.x+b.width/2)*VIEW.scale,(b.bottom+b.top)/2*VIEW.scale,(b.y+b.height/2)*VIEW.scale);mesh.scale.set(b.width*VIEW.scale,(b.top-b.bottom)*VIEW.scale,b.height*VIEW.scale);mesh.name='collision:'+b.id;this.root.add(mesh);this.solids.push(mesh);}
 slope(s:Surface,mat:T.Material,trim:T.Material){const corners=[[s.x,s.y],[s.x+s.width,s.y],[s.x+s.width,s.y+s.height],[s.x,s.y+s.height]],bottom=Math.min(s.ramp!.from,s.ramp!.to);const geometry=this.track(new T.BufferGeometry());geometry.setAttribute('position',new T.Float32BufferAttribute([...corners.flatMap(([x,y])=>[x*VIEW.scale,surfaceHeight(s,{x,y})*VIEW.scale,y*VIEW.scale]),...corners.flatMap(([x,y])=>[x*VIEW.scale,bottom*VIEW.scale,y*VIEW.scale])],3));geometry.setIndex([0,3,2,0,2,1,4,1,5,4,0,1,5,2,6,5,1,2,6,3,7,6,2,3,7,0,4,7,3,0]);geometry.computeVertexNormals();const mesh=new T.Mesh(geometry,mat);mesh.name='slope:'+s.id;this.root.add(mesh);this.solids.push(mesh);
  const xAxis=s.ramp!.axis==='x',length=xAxis?s.width:s.height,count=s.style==='stairs'?Math.max(5,Math.ceil(Math.abs(s.ramp!.to-s.ramp!.from)/4)):Math.ceil(length/40);for(let i=0;i<count;i++){const t=(i+.5)/count,e=s.ramp!.from+(s.ramp!.to-s.ramp!.from)*t,step=length/count;this.box(s.x+(xAxis?i*step:0),s.y+(xAxis?0:i*step),xAxis?step:s.width,xAxis?s.height:step,e-.6,1.2,i%4===0?trim:mat);}
 }
 finish(){for(const {geometry,material,matrices} of this.batches.values()){const mesh=this.track(new T.InstancedMesh(geometry,material,matrices.length));matrices.forEach((matrix,i)=>mesh.setMatrixAt(i,matrix));mesh.instanceMatrix.needsUpdate=true;mesh.computeBoundingSphere();mesh.name='district-static-batch';this.root.add(mesh);}this.batches.clear();this.root.updateMatrixWorld(true);}
 dispose(){this.scene.remove(this.root);this.resources.forEach(r=>r.dispose());this.resources.clear();this.root.clear();this.solids.length=0;}
}
