import type {Rig} from '../characters/rig';
export const animations=[{id:'idle',name:'Idle',category:'Locomotion',status:'implemented',duration:3},{id:'walk',name:'Walk',category:'Locomotion',status:'experimental',duration:1.2},{id:'run',name:'Run',category:'Locomotion',status:'experimental',duration:.8},{id:'sprint',name:'Sprint',category:'Locomotion',status:'experimental',duration:.65},{id:'strafe-left',name:'Strafe left',category:'Locomotion',status:'not created',duration:1},{id:'strafe-right',name:'Strafe right',category:'Locomotion',status:'not created',duration:1},{id:'backward',name:'Walk backward',category:'Locomotion',status:'not created',duration:1},{id:'jump',name:'Jump',category:'Movement',status:'not created',duration:1},{id:'land',name:'Land',category:'Movement',status:'not created',duration:1},{id:'dash',name:'Dash',category:'Movement',status:'experimental',duration:.7},{id:'turn',name:'Turn',category:'Movement',status:'not created',duration:1},{id:'attack',name:'Attack 1',category:'Combat',status:'experimental',duration:1},{id:'attack2',name:'Attack 2',category:'Combat',status:'not created',duration:1},{id:'attack3',name:'Attack 3',category:'Combat',status:'not created',duration:1},{id:'hit',name:'Hit reaction',category:'Combat',status:'experimental',duration:.7},...['Knockback','Elimination','Target acquired','Bounty earned','Round win','Match win'].map(name=>({id:name.toLowerCase().replaceAll(' ','-'),name,category:['Knockback','Elimination'].includes(name)?'Combat':'Bounty / gameplay',status:'not created',duration:1}))];
export const defaults={cadence:1,stride:.55,armSwing:.45,kneeBend:.75,twist:.12,bob:.055,lean:.15,windup:.3,strike:.45};
export type Params=typeof defaults;
export function animate(r:Rig,id:string,phase:number,p:Params){
 r.joints.forEach(j=>j.rotation.set(0,0,0));r.hips.position.set(0,r.restHipsY,0);const t=phase*Math.PI*2;
 if(id==='idle'){r.torso.scale.y=1+Math.sin(t)*.008;r.head.rotation.y=Math.sin(t)*.07;r.arms.forEach((a,i)=>a.shoulder.rotation.z=(i?1:-1)*.055);return;}
 r.torso.scale.y=1;
 if(['walk','run','sprint'].includes(id)){const intensity=id==='walk'?1:id==='run'?1.35:1.65,s=Math.sin(t),lift=Math.sin(t*2);r.hips.position.y+=p.bob*(1-Math.cos(t*2));r.hips.rotation.y=-s*p.twist*.5;r.torso.rotation.y=s*p.twist;r.torso.rotation.x=p.lean*(intensity-0.55);r.head.rotation.y=-r.torso.rotation.y*.65;r.head.rotation.x=-r.torso.rotation.x*.6;r.legs.forEach((leg,i)=>{const a=t+i*Math.PI;leg.hip.rotation.x=Math.sin(a)*p.stride*intensity;leg.knee.rotation.x=Math.max(0,-Math.sin(a)) *p.kneeBend*intensity;leg.ankle.rotation.x=-leg.hip.rotation.x*.35-leg.knee.rotation.x*.55;});r.arms.forEach((arm,i)=>{arm.shoulder.rotation.x=-Math.sin(t+i*Math.PI)*p.armSwing*intensity;arm.elbow.rotation.x=-.15-(intensity-1)*.9-Math.max(0,Math.sin(t+i*Math.PI))*.2;});r.torso.rotation.z=lift*.018;return;}
 const pulse=Math.sin(Math.PI*Math.min(1,phase));
 if(id==='dash'){r.hips.position.y-=pulse*.22;r.torso.rotation.x=pulse*.65;r.arms.forEach(a=>a.shoulder.rotation.x=pulse*.8);r.legs[0].hip.rotation.x=-pulse*.65;r.legs[1].hip.rotation.x=pulse*.8;r.legs[1].knee.rotation.x=pulse*.9;}
 if(id==='attack'){const amount=phase<p.windup?-phase/p.windup*.6:phase<p.strike?-.6+(phase-p.windup)/(p.strike-p.windup)*1.6:(1-phase)/(1-p.strike);r.torso.rotation.y=-amount*.6;r.arms[1].shoulder.rotation.x=-amount*1.65;r.arms[1].elbow.rotation.x=-.8*(1-Math.max(0,amount));r.arms[0].elbow.rotation.x=-.7;r.hips.rotation.y=-amount*.2;}
 if(id==='hit'){r.torso.rotation.x=-pulse*.4;r.head.rotation.x=-pulse*.25;r.hips.position.z=-pulse*.22;r.arms.forEach(a=>a.shoulder.rotation.x=-pulse*.3);}
}
export function advance(time:number,delta:number,duration:number,loop:boolean){const next=time+delta;return {time:loop?next%duration:Math.min(next,duration),playing:loop||next<duration};}

