import assert from 'node:assert/strict';
import { chromium as browserEngine } from 'playwright-core';
import { mkdir } from 'node:fs/promises';
import { resolve } from 'node:path';
import { tmpdir } from 'node:os';
process.env.BOUNTY_TEST='1';
const {createGameServer}=await import('../server/index.ts');
const game=await createGameServer(true);await new Promise(r=>game.server.listen(0,'127.0.0.1',r));const url=`http://127.0.0.1:${game.server.address().port}`;
const output=resolve(process.env.BOUNTY_QA_OUTPUT||resolve(tmpdir(),'bounty-shift-qa'));await mkdir(output,{recursive:true});
let browser;
try{
 browser=await browserEngine.launch({executablePath:process.env.BOUNTY_QA_BROWSER||undefined,args:['--no-sandbox','--no-zygote','--enable-webgl','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader'],headless:true});
 const ca=await browser.newContext({viewport:{width:1440,height:1050}}),cb=await browser.newContext({viewport:{width:390,height:844},hasTouch:true,isMobile:true});const a=await ca.newPage(),b=await cb.newPage();const errors=[];for(const p of [a,b])p.on('pageerror',e=>errors.push(e.message));
 await a.goto(url);await a.getByLabel('Display name').fill('goichi');await a.getByRole('button',{name:'Create room'}).click();await a.locator('.code').waitFor();const code=await a.locator('.code').textContent();
 await b.goto(url);await b.getByLabel('Display name').fill('Aizen');await b.getByLabel('Room code').fill(code);await b.getByRole('button',{name:'Join room'}).click();await b.getByRole('button',{name:'Ready up'}).click();await a.getByRole('button',{name:'Ready up'}).click();await a.getByRole('button',{name:'Start match',exact:true}).click();await a.locator('.viewport canvas').waitFor();await b.locator('.viewport canvas').waitFor();await a.waitForTimeout(1300);
 // Verify containment of actual gameplay content, not only hidden document overflow.
 const sizes=[[1920,1080],[1440,900],[1366,768],[1280,720],[1024,600],[800,450],[640,360],[390,844],[375,667],[320,568],[844,390]];
 async function checkLayout(page){
  const metrics=await page.evaluate(()=>{
   const selectors=['.game-screen>header','.objective','.viewport','.game-hud','.hint','.legend','.touch-controls','.game-hud label','.game-hud span','.game-hud progress','.touch-controls button','.legend li','.minimap','.arena-section>.panel>*'];
   const items=selectors.flatMap(s=>[...document.querySelectorAll(s)]).filter(e=>getComputedStyle(e).display!=='none').map(e=>{const r=e.getBoundingClientRect();return {name:e.className||e.tagName,x:r.x,y:r.y,right:r.right,bottom:r.bottom,height:r.height};});
   return {width:innerWidth,height:innerHeight,scrollWidth:document.documentElement.scrollWidth,scrollHeight:document.documentElement.scrollHeight,items};
  });
  assert(metrics.scrollWidth<=metrics.width&&metrics.scrollHeight<=metrics.height,JSON.stringify(metrics));
  for(const r of metrics.items)assert(r.x>=-1&&r.y>=-1&&r.right<=metrics.width+1&&r.bottom<=metrics.height+1,JSON.stringify(r));
  const arena=metrics.items.find(r=>r.name==='viewport');
  if(arena)assert(arena.height>=metrics.height*.35,'Arena must remain a substantial part of the viewport: '+JSON.stringify(metrics));
 }
 for(const [width,height] of sizes){await a.setViewportSize({width,height});await a.waitForTimeout(80);await checkLayout(a);}
 await a.mouse.wheel(0,500);assert.equal(await a.evaluate(()=>scrollY),0);
 await a.setViewportSize({width:1366,height:768});await a.waitForTimeout(100);
 await a.screenshot({path:resolve(output,'STEP2_PREVIEW.png'),fullPage:true});
 const room=game.rooms.rooms.get(code),self=room.players.find(p=>p.name==='goichi');const oldX=self.x;
 await a.keyboard.down('w');await a.waitForTimeout(600);await a.keyboard.up('w');await a.waitForTimeout(150);assert(self.x>oldX+40,'Camera-relative forward follows initial plaza-facing view');
 // Real desktop pointer lock: activation click does not attack or move the body.
 const stationary={x:self.x,y:self.y,fx:self.facingX,fy:self.facingY},attackSeen=self.attackSeen;
 await a.locator('.viewport canvas').click();await a.waitForFunction(()=>document.pointerLockElement===document.querySelector('canvas'));
 const beforeLook=await a.locator('.viewport').screenshot();await a.mouse.move(850,360);await a.mouse.move(1050,270);await a.waitForTimeout(250);
 assert.equal(self.x,stationary.x);assert.equal(self.y,stationary.y);assert.equal(self.facingX,stationary.fx);assert.equal(self.facingY,stationary.fy);assert.equal(self.attackSeen,attackSeen);
 const afterLook=await a.locator('.viewport').screenshot();assert(!beforeLook.equals(afterLook),'Stationary mouse look changes rendered camera');
 await a.mouse.down();await a.mouse.up();await a.waitForTimeout(150);assert(self.attackSeen>attackSeen,'Locked left click remains attack');
 await a.keyboard.down('w');await a.waitForTimeout(200);await a.mouse.move(1250,340);await a.waitForTimeout(250);await a.keyboard.up('w');assert(Math.hypot(self.x-stationary.x,self.y-stationary.y)>20);
 await a.keyboard.press('Escape');await a.waitForFunction(()=>!document.pointerLockElement);
 // Two real touch contacts via Chromium's input dispatch, independent pointer IDs.
 const mobile=await cb.newCDPSession(b),joy=await b.locator('.joystick').boundingBox(),view=await b.locator('.viewport').boundingBox();assert(joy&&view);
 const other=room.players.find(p=>p.name==='Aizen'),oldOther={x:other.x,y:other.y};
 const left={id:1,x:joy.x+joy.width/2,y:joy.y+joy.height/2-35},right={id:2,x:view.x+view.width*.75,y:view.y+view.height*.45};
 const idleTouchBefore=await b.locator('.viewport').screenshot();
 await mobile.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[right]});right.x+=35;right.y-=20;
 await mobile.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[right]});await b.waitForTimeout(250);
 await mobile.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
 assert.equal(other.x,oldOther.x);assert.equal(other.y,oldOther.y);
 assert(!idleTouchBefore.equals(await b.locator('.viewport').screenshot()),'Stationary touch look changes camera');

 await mobile.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[left,right]});await b.waitForTimeout(200);
 right.x+=40;right.y-=25;await mobile.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[left,right]});await b.waitForTimeout(350);
 assert(Math.hypot(other.x-oldOther.x,other.y-oldOther.y)>20,'Joystick moves while camera finger swipes');
 await mobile.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await b.waitForTimeout(120);
 const released={x:other.x,y:other.y};await b.waitForTimeout(200);assert(Math.hypot(other.x-released.x,other.y-released.y)<2,'Touch release clears movement');
 await b.screenshot({path:resolve(output,'STAGE2_MOBILE_PREVIEW.png'),fullPage:true});
 await a.keyboard.down('e');await a.waitForTimeout(250);await a.keyboard.up('e');await a.keyboard.down('Shift');await a.keyboard.down('w');await a.waitForTimeout(200);await a.keyboard.press('Space');await a.keyboard.up('w');await a.keyboard.up('Shift');await a.waitForTimeout(200);assert(self.stamina<100);assert(self.dashCooldown>0);
 // Server fixture places an opponent within the reticle-facing range; no test endpoint added.
 await a.getByRole('button',{name:'Return everyone to lobby'}).click();await a.getByRole('button',{name:'Ready up'}).click();await b.getByRole('button',{name:'Ready up'}).click();await a.getByRole('button',{name:'Start match',exact:true}).click();await a.locator('.viewport canvas').waitFor();await a.waitForTimeout(200);const victim=room.players.find(p=>p.name==='Aizen');
 // Walk the real client up the west stairs. A/D/W vectors are relative to the retained local camera.
 Object.assign(self,{x:730,y:1900,elevation:0,spawnVersion:self.spawnVersion+1});await a.waitForTimeout(200);
 await a.keyboard.down('q');await a.waitForTimeout(280);await a.keyboard.up('q');await a.waitForTimeout(100);
 await a.keyboard.down('Shift');await a.keyboard.down('w');await a.waitForTimeout(1550);await a.keyboard.up('w');await a.keyboard.up('Shift');await a.waitForTimeout(200);
 assert.equal(self.elevation,100,'Browser-controlled sprint climbs to upper walkway');
 const marker=await a.locator('.minimap svg > g:last-child').getAttribute('transform');const coords=marker.match(/translate\(([^ ]+) ([^)]+)\)/);assert(Math.abs(+coords[1]-self.x)<5&&Math.abs(+coords[2]-self.y)<5,'Minimap marker tracks authoritative X/Z at height');
 Object.assign(self,{x:985,y:1450,elevation:100,spawnVersion:self.spawnVersion+1});await a.keyboard.down('e');await a.waitForTimeout(280);await a.keyboard.up('e');await a.waitForTimeout(150);
 // Reset camera pitch for a reproducible upper-route preview through the normal look listener.
 await a.locator('.viewport canvas').click();await a.waitForFunction(()=>!!document.pointerLockElement);
 await a.waitForTimeout(80);await a.evaluate(()=>{for(const value of [10000,-280]){const event=new MouseEvent('mousemove');Object.defineProperty(event,'movementY',{value});document.dispatchEvent(event);}});await a.waitForTimeout(200);
 await a.keyboard.down('w');await a.waitForTimeout(80);await a.keyboard.up('w');await a.waitForTimeout(100);
 const heading=Math.atan2(self.facingX,-self.facingY),towardPlaza=Math.atan2(1300-self.x,-(1060-self.y));
 await a.evaluate(delta=>{const event=new MouseEvent('mousemove');Object.defineProperty(event,'movementX',{value:delta});document.dispatchEvent(event);},Math.atan2(Math.sin(towardPlaza-heading),Math.cos(towardPlaza-heading))/.0028);await a.waitForTimeout(250);
 await a.keyboard.down('w');await a.waitForTimeout(80);await a.keyboard.up('w');await a.waitForTimeout(150);await a.keyboard.press('Escape');await a.waitForTimeout(100);
 await a.screenshot({path:resolve(output,'CENTRAL_PLAZA_PREVIEW.png'),fullPage:true});
 Object.assign(victim,{x:1620,y:1450,elevation:100,spawnVersion:victim.spawnVersion+1});await b.waitForTimeout(400);await b.screenshot({path:resolve(output,'CENTRAL_PLAZA_MOBILE_PREVIEW.png'),fullPage:true});
 Object.assign(self,{x:1000,y:700,elevation:0,spawnVersion:self.spawnVersion+1});await a.waitForTimeout(250);
 // Preview free-look deliberately changes orientation; place the melee fixture along the actual camera-forward movement, not a fixed world axis.
 await a.keyboard.down('w');await a.waitForTimeout(110);await a.keyboard.up('w');await a.waitForTimeout(180);
 Object.assign(victim,{x:self.x+self.facingX*40,y:self.y+self.facingY*40,elevation:0,spawnVersion:victim.spawnVersion+1});await a.waitForTimeout(250);await a.keyboard.press('f');await a.waitForTimeout(200);assert.equal(victim.health,75);await b.waitForFunction(()=>document.querySelector('.game-hud')?.textContent.includes('75 / 100'));
 await a.reload();await a.locator('.viewport canvas').waitFor();assert.equal(room.players.length,2);await a.waitForTimeout(300);
 await a.setViewportSize({width:390,height:844});await a.screenshot({path:resolve(output,'STEP2_MOBILE_PREVIEW.png'),fullPage:true});assert.equal(await a.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'No horizontal overflow');
 for(let n=1;n<=3;n++){
  const expected=n===3?'aerie_sky_port':n===2?'scorched_point':'central_plaza';assert.equal(room.mapId,expected);
  for(const page of [a,b]){await page.waitForFunction(map=>document.querySelector('.viewport canvas')?.dataset.mapId===map,expected);assert.equal(await page.locator('.viewport canvas').count(),1);assert.equal(await page.locator('.minimap').count(),1);}
  if(n===2){
   // Normalize the visual countdown after accelerated intermission fixtures; real-duration checks run separately.
   room.round.endsAt=Date.now()+90000;
   assert.equal(await a.locator('.minimap-title').textContent(),'SCORCHED POINT N ↑');assert.equal(await b.locator('.minimap-title').textContent(),'SCORCHED POINT N ↑');
   await a.setViewportSize({width:1366,height:768});await a.locator('.viewport canvas').focus();await a.waitForTimeout(150);await a.keyboard.down('w');await a.keyboard.down('Shift');await a.waitForTimeout(1300);await a.keyboard.up('w');await a.keyboard.up('Shift');await a.waitForTimeout(150);assert.equal(self.elevation,90,'Real client climbs refinery ramp into Crucible: '+JSON.stringify({x:self.x,y:self.y,dx:self.dx,dy:self.dy,fx:self.facingX,fy:self.facingY,health:self.health,seq:self.seq}));
   const beforeDash={x:self.x,y:self.y};await a.keyboard.press('Space');await a.waitForTimeout(300);assert(self.dashCooldown>0);assert(Math.hypot(self.x-beforeDash.x,self.y-beforeDash.y)>5);
   Object.assign(self,{x:1100,y:970,elevation:90,facingX:1,facingY:0,spawnVersion:self.spawnVersion+1});Object.assign(victim,{x:1140,y:970,elevation:90,health:100,spawnVersion:victim.spawnVersion+1});await a.reload();await a.locator('.viewport canvas').waitFor();await a.waitForTimeout(200);
   // Melee along the current map-facing camera vector using ordinary F input.
   await a.keyboard.down('w');await a.waitForTimeout(100);await a.keyboard.up('w');await a.waitForTimeout(180);Object.assign(victim,{x:self.x+self.facingX*40,y:self.y+self.facingY*40,elevation:90,spawnVersion:victim.spawnVersion+1});await a.waitForTimeout(150);await a.keyboard.press('f');await a.waitForTimeout(250);assert.equal(victim.health,75);await b.waitForFunction(()=>document.querySelector('.game-hud')?.textContent.includes('75 / 100'));
   Object.assign(self,{x:790,y:1180,elevation:190,facingX:1,facingY:0,spawnVersion:self.spawnVersion+1});Object.assign(victim,{x:1400,y:1100,elevation:90,health:100,spawnVersion:victim.spawnVersion+1});await a.reload();await a.locator('.viewport canvas').waitFor();await a.waitForTimeout(500);assert.equal(await a.locator('.viewport canvas').getAttribute('data-map-id'),'scorched_point');assert.equal(room.players.length,2);await a.screenshot({path:resolve(output,'SCORCHED_POINT_PREVIEW.png'),fullPage:true});
   Object.assign(victim,{x:1600,y:1200,elevation:190,spawnVersion:victim.spawnVersion+1});await b.reload();await b.locator('.viewport canvas').waitFor();await b.waitForTimeout(300);assert.equal(await b.locator('.viewport canvas').getAttribute('data-map-id'),'scorched_point');
   const joy2=await b.locator('.joystick').boundingBox(),view2=await b.locator('.viewport').boundingBox();const l2={id:7,x:joy2.x+joy2.width/2,y:joy2.y+joy2.height/2-30},r2={id:8,x:view2.x+view2.width*.8,y:view2.y+view2.height*.4};
   const sprint2=await b.getByRole('button',{name:'Sprint',exact:true}).boundingBox(),s2={id:9,x:sprint2.x+sprint2.width/2,y:sprint2.y+sprint2.height/2};const oldTouch={x:victim.x,y:victim.y};await mobile.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[l2,r2,s2]});r2.x+=30;await mobile.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[l2,r2,s2]});await b.waitForTimeout(200);await mobile.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert(Math.hypot(victim.x-oldTouch.x,victim.y-oldTouch.y)>5);assert(victim.stamina<100,'Touch sprint remains active while joystick and look pointers run');await b.getByRole('button',{name:'Dash',exact:true}).tap();await b.waitForTimeout(150);assert(victim.dashCooldown>0);await b.getByRole('button',{name:'Attack',exact:true}).tap();await b.waitForTimeout(150);assert(victim.attackCooldown>0);
   await b.screenshot({path:resolve(output,'SCORCHED_POINT_MOBILE_PREVIEW.png'),fullPage:true});await checkLayout(b);
   for(const [width,height] of sizes){await a.setViewportSize({width,height});await a.waitForTimeout(60);await checkLayout(a);}await a.setViewportSize({width:390,height:844});
  }
  if(n===3){
   room.round.endsAt=Date.now()+90000;
   for(const page of [a,b]){assert.equal(await page.locator('.viewport canvas').getAttribute('data-map-variant'),'day');assert.equal(await page.locator('.minimap-title').textContent(),'AERIE SKY-PORT N ↑');await checkLayout(page);}
   await a.setViewportSize({width:1366,height:768});Object.assign(self,{x:1100,y:1120,elevation:0,spawnVersion:self.spawnVersion+1});await a.reload();await a.locator('.viewport canvas').waitFor();await a.waitForTimeout(300);await a.locator('.viewport canvas').click();await a.waitForFunction(()=>!!document.pointerLockElement);await a.keyboard.down('w');await a.waitForTimeout(100);await a.keyboard.up('w');await a.waitForTimeout(200);const ah=Math.atan2(self.facingX,-self.facingY);await a.evaluate(delta=>{const event=new MouseEvent('mousemove');Object.defineProperty(event,'movementX',{value:delta});document.dispatchEvent(event);},Math.atan2(Math.sin(-ah),Math.cos(-ah))/.0028);Object.assign(self,{x:1100,y:1120,elevation:0,spawnVersion:self.spawnVersion+1});await a.waitForTimeout(300);await a.keyboard.down('w');await a.keyboard.down('Shift');for(let wait=0;wait<40&&self.elevation!==90;wait++)await a.waitForTimeout(200);await a.keyboard.up('w');await a.keyboard.up('Shift');await a.waitForTimeout(100);assert.equal(self.elevation,90,'Aerie main stairs climb with keyboard sprint '+JSON.stringify({x:self.x,y:self.y,fx:self.facingX,fy:self.facingY}));await a.keyboard.press('Escape');await a.screenshot({path:resolve(output,'AERIE_DAY_PREVIEW.png'),fullPage:true});
   const aj=await b.locator('.joystick').boundingBox(),av=await b.locator('.viewport').boundingBox(),as=await b.getByRole('button',{name:'Sprint',exact:true}).boundingBox();const al={id:21,x:aj.x+aj.width/2,y:aj.y+aj.height/2-30},ar={id:22,x:av.x+av.width*.8,y:av.y+av.height*.4},ap={id:23,x:as.x+as.width/2,y:as.y+as.height/2};const previous={x:victim.x,y:victim.y};await mobile.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[al,ar,ap]});ar.x+=25;await mobile.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[al,ar,ap]});await b.waitForTimeout(220);await mobile.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert(Math.hypot(victim.x-previous.x,victim.y-previous.y)>5);assert(victim.stamina<100);await b.getByRole('button',{name:'Dash',exact:true}).tap();await b.waitForTimeout(150);assert(victim.dashCooldown>0);await b.getByRole('button',{name:'Attack',exact:true}).tap();await b.waitForTimeout(150);assert(victim.attackCooldown>0);await b.screenshot({path:resolve(output,'AERIE_MOBILE_PREVIEW.png'),fullPage:true});for(const [width,height] of sizes){await a.setViewportSize({width,height});await a.waitForTimeout(60);await checkLayout(a);}await a.setViewportSize({width:1366,height:768});
  }
  game.rooms.tick(room.round.endsAt);await a.getByRole('heading',{name:n===3?'MATCH COMPLETE':'Round complete',exact:true}).waitFor();await checkLayout(a);if(n<3){room.nextMapId=n===1?'scorched_point':'aerie_sky_port';room.nextMapVariant=n===2?'day':null;game.rooms.tick(room.round.returnAt);await a.locator('.viewport canvas').waitFor();await a.waitForTimeout(150);}}assert.equal(room.phase,'complete');assert.deepEqual(room.match.mapHistory,['central_plaza','scorched_point','aerie_sky_port']);
 await (room.hostId===self.id?a:b).getByRole('button',{name:'Return everyone to lobby'}).click();await a.getByRole('button',{name:'Ready up'}).waitFor();assert(room.players.every(p=>p.matchEliminations===0&&p.targetId===null));assert.equal(await a.evaluate(()=>document.documentElement.classList.contains('match-open')),false,'Lobby restores normal page flow');
 await a.getByRole('button',{name:'Ready up'}).click();await b.getByRole('button',{name:'Ready up'}).click();await (room.hostId===self.id?a:b).getByRole('button',{name:'Start match',exact:false}).click();await a.locator('.viewport canvas').waitFor();assert.equal(room.mapId,'central_plaza');game.rooms.tick(room.round.endsAt);room.nextMapId='aerie_sky_port';room.nextMapVariant='night';game.rooms.tick(room.round.returnAt);room.round.endsAt=Date.now()+90000;
 for(const page of [a,b]){await page.waitForFunction(()=>document.querySelector('.viewport canvas')?.dataset.mapVariant==='night');assert.equal(await page.locator('.viewport canvas').getAttribute('data-map-id'),'aerie_sky_port');await checkLayout(page);}
 Object.assign(self,{x:1100,y:1450,elevation:0,spawnVersion:self.spawnVersion+1});await a.reload();await a.locator('.viewport canvas').waitFor();await a.waitForTimeout(400);assert.equal(await a.locator('.viewport canvas').getAttribute('data-map-variant'),'night');await a.screenshot({path:resolve(output,'AERIE_NIGHT_PREVIEW.png'),fullPage:true});

 // Private test fixture guarantees Aerie Night -> Canyon coverage; production selection remains random.
 game.rooms.tick(room.round.endsAt);room.nextMapId='outlaws_canyon';room.nextMapVariant=null;game.rooms.tick(room.round.returnAt);room.round.endsAt=Date.now()+90000;
 for(const page of [a,b]){await page.waitForFunction(()=>document.querySelector('.viewport canvas')?.dataset.mapId==='outlaws_canyon');assert.equal(await page.locator('.viewport canvas').getAttribute('data-map-variant'),null);assert.equal(await page.locator('.minimap-title').textContent(),"OUTLAW'S CANYON N ↑");assert.equal(await page.locator('.minimap').count(),1);await checkLayout(page);}
 assert.equal(room.match.roundNumber,3);assert.equal(room.mapVariant,null);assert.equal(room.players.length,2);
 Object.assign(self,{x:1080,y:900,elevation:0,spawnVersion:self.spawnVersion+1});await a.reload();await a.locator('.viewport canvas').waitFor();await a.waitForTimeout(250);await a.locator('.viewport canvas').click();await a.waitForFunction(()=>!!document.pointerLockElement);for(let turn=0;turn<3;turn++){await a.keyboard.press('f');await a.waitForTimeout(150);const ch=Math.atan2(self.aimX,-self.aimY);await a.evaluate(delta=>{const event=new MouseEvent('mousemove');Object.defineProperty(event,'movementX',{value:delta});document.dispatchEvent(event);},Math.atan2(Math.sin(-Math.PI/2-ch),Math.cos(-Math.PI/2-ch))/.0028);await a.waitForTimeout(250);}Object.assign(self,{x:1080,y:900,elevation:0,spawnVersion:self.spawnVersion+1});await a.waitForTimeout(300);await a.keyboard.down('w');await a.keyboard.down('Shift');await a.waitForTimeout(1300);await a.keyboard.up('w');await a.keyboard.up('Shift');await a.waitForTimeout(150);assert.equal(self.elevation,80,'Canyon porch climb '+JSON.stringify({x:self.x,y:self.y,fx:self.facingX,fy:self.facingY}));
 await a.waitForTimeout(300);await a.waitForFunction(p=>{const t=document.querySelector('.minimap svg > g:last-child')?.getAttribute('transform'),c=t?.match(/translate\(([^ ]+) ([^)]+)\)/);return c&&Math.abs(+c[1]-p.x)<5&&Math.abs(+c[2]-p.y)<5;},{x:self.x,y:self.y},{timeout:5000});
 const cm=await a.locator('.minimap svg > g:last-child').getAttribute('transform'),cc=cm.match(/translate\(([^ ]+) ([^)]+)\)/);assert(Math.abs(+cc[1]-self.x)<5&&Math.abs(+cc[2]-self.y)<5);
 Object.assign(victim,{x:self.x+self.facingX*40,y:self.y+self.facingY*40,elevation:80,health:100,protection:0,spawnVersion:victim.spawnVersion+1});await a.waitForTimeout(200);await a.keyboard.press('f');await a.waitForTimeout(220);assert.equal(victim.health,75);await b.waitForFunction(()=>document.querySelector('.game-hud')?.textContent.includes('75 / 100'));
 await a.keyboard.press('Space');await a.waitForTimeout(200);assert(self.dashCooldown>0);await a.keyboard.press('Escape');
 Object.assign(self,{x:1100,y:1100,elevation:0,spawnVersion:self.spawnVersion+1});Object.assign(victim,{x:1070,y:850,elevation:0,health:100,spawnVersion:victim.spawnVersion+1});await a.reload();await a.locator('.viewport canvas').waitFor();await a.waitForTimeout(450);assert.equal(await a.locator('.viewport canvas').getAttribute('data-map-id'),'outlaws_canyon');await a.screenshot({path:resolve(output,'OUTLAW_CANYON_PREVIEW.png'),fullPage:true});
 Object.assign(victim,{x:900,y:1300,elevation:0,spawnVersion:victim.spawnVersion+1});await b.reload();await b.locator('.viewport canvas').waitFor();await b.waitForTimeout(250);const oj=await b.locator('.joystick').boundingBox(),ov=await b.locator('.viewport').boundingBox(),os=await b.getByRole('button',{name:'Sprint',exact:true}).boundingBox();const ol={id:31,x:oj.x+oj.width/2,y:oj.y+oj.height/2-30},or={id:32,x:ov.x+ov.width*.8,y:ov.y+ov.height*.4},op={id:33,x:os.x+os.width/2,y:os.y+os.height/2};const oldC={x:victim.x,y:victim.y};await mobile.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[ol,or,op]});or.x+=25;await mobile.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[ol,or,op]});await b.waitForTimeout(220);await mobile.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert(Math.hypot(victim.x-oldC.x,victim.y-oldC.y)>5);assert(victim.stamina<100);await b.getByRole('button',{name:'Dash',exact:true}).tap();await b.waitForTimeout(150);assert(victim.dashCooldown>0);await b.getByRole('button',{name:'Attack',exact:true}).tap();await b.waitForTimeout(150);assert(victim.attackCooldown>0);await checkLayout(b);await b.screenshot({path:resolve(output,'OUTLAW_CANYON_MOBILE_PREVIEW.png'),fullPage:true});
 for(const [width,height] of sizes){await a.setViewportSize({width,height});await a.waitForTimeout(60);await checkLayout(a);}game.rooms.tick(room.round.endsAt);await a.getByRole('heading',{name:'MATCH COMPLETE',exact:true}).waitFor();assert.deepEqual(room.match.mapHistory,['central_plaza','aerie_sky_port','outlaws_canyon']);await (room.hostId===self.id?a:b).getByRole('button',{name:'Return everyone to lobby'}).click();await a.getByRole('button',{name:'Ready up'}).waitFor();assert.equal(room.mapId,'central_plaza');assert.equal(room.mapVariant,null);
 // A third complete two-client match covers Map 5 and teardown back to another arena.
 await a.setViewportSize({width:1366,height:768});await a.getByRole('button',{name:'Ready up'}).click();await b.getByRole('button',{name:'Ready up'}).click();await (room.hostId===self.id?a:b).getByRole('button',{name:'Start match',exact:false}).click();await a.locator('.viewport canvas').waitFor();assert.equal(room.mapId,'central_plaza');assert.equal(room.match.totalRounds,3);
 game.rooms.tick(room.round.endsAt);room.nextMapId='vikings_fjord';room.nextMapVariant=null;game.rooms.tick(room.round.returnAt);room.round.endsAt=Date.now()+90000;
 for(const page of [a,b]){await page.waitForFunction(()=>document.querySelector('.viewport canvas')?.dataset.mapId==='vikings_fjord');assert.equal(await page.locator('.viewport canvas').getAttribute('data-map-variant'),null);assert.equal(await page.locator('.minimap-title').textContent(),"VIKING'S FJORD N ↑");assert.equal(await page.locator('.minimap').count(),1);await checkLayout(page);}
 assert.equal(room.match.roundNumber,2);assert.equal(room.players.length,2);assert.equal(room.mapVariant,null);
 async function fjordDirection(yaw){for(let turn=0;turn<8;turn++){await a.waitForTimeout(350);const previous=self.attackId;await a.keyboard.press('f');for(let wait=0;wait<20&&self.attackId===previous;wait++)await a.waitForTimeout(100);const current=Math.atan2(self.aimX,-self.aimY),error=Math.atan2(Math.sin(yaw-current),Math.cos(yaw-current));if(Math.abs(error)<.002)return;await a.evaluate(delta=>{const event=new MouseEvent('mousemove');Object.defineProperty(event,'movementX',{value:delta});document.dispatchEvent(event);},error/.0028);}throw Error('Camera direction calibration did not settle');}
 Object.assign(self,{x:1030,y:1130,elevation:0,spawnVersion:self.spawnVersion+1});await a.reload();await a.locator('.viewport canvas').waitFor();await a.waitForTimeout(250);await a.locator('.viewport canvas').click();await a.waitForFunction(()=>!!document.pointerLockElement);await fjordDirection(0);Object.assign(self,{x:1030,y:1130,elevation:0,spawnVersion:self.spawnVersion+1});await a.waitForTimeout(300);await a.keyboard.down('w');await a.keyboard.down('Shift');for(let wait=0;wait<40&&self.elevation!==90;wait++)await a.waitForTimeout(200);await a.keyboard.up('w');await a.keyboard.up('Shift');await a.waitForTimeout(300);assert.equal(self.elevation,90,'Valhalla stairs climb using existing browser controller');assert(self.stamina<100);
 Object.assign(self,{x:1360,y:650,elevation:90,stamina:100,exhausted:false,spawnVersion:self.spawnVersion+1});await a.waitForTimeout(450);await fjordDirection(0);await a.keyboard.down('w');await a.keyboard.down('Shift');for(let wait=0;wait<40&&self.elevation!==180;wait++)await a.waitForTimeout(200);await a.keyboard.up('w');await a.keyboard.up('Shift');await a.waitForTimeout(300);assert.equal(self.elevation,180,'Northern battlement reaches third height band '+JSON.stringify({x:self.x,y:self.y,fx:self.facingX,fy:self.facingY,aimX:self.aimX,aimY:self.aimY}));
 await a.waitForFunction(p=>{const c=document.querySelector('.minimap svg > g:last-child')?.getAttribute('transform')?.match(/translate\(([^ ]+) ([^)]+)\)/);return c&&Math.abs(+c[1]-p.x)<5&&Math.abs(+c[2]-p.y)<5;},{x:self.x,y:self.y},{timeout:5000});
 await fjordDirection(Math.PI);Object.assign(self,{x:1560,y:1310,elevation:0,spawnVersion:self.spawnVersion+1});await a.waitForTimeout(300);await a.keyboard.down('w');await a.keyboard.down('Shift');for(let wait=0;wait<40&&self.y<1640;wait++)await a.waitForTimeout(200);await a.keyboard.up('w');await a.keyboard.up('Shift');await a.waitForTimeout(250);assert(self.y>1620&&self.elevation===0,'Camera/controller traverse the wide ice cave');
 Object.assign(self,{x:1410,y:1800,elevation:0,stamina:100,exhausted:false,spawnVersion:self.spawnVersion+1});await a.waitForTimeout(300);await a.keyboard.down('w');await a.keyboard.down('Shift');for(let wait=0;wait<40&&self.elevation!==80;wait++)await a.waitForTimeout(200);await a.keyboard.up('w');await a.keyboard.up('Shift');await a.waitForTimeout(250);assert.equal(self.elevation,80,'Dock stairs and snow-covered quay are playable');await a.keyboard.press('Space');await a.waitForTimeout(200);assert(self.dashCooldown>0);
 // Same-floor melee remains server-authoritative, including Bounty health synchronization.
 Object.assign(self,{x:950,y:1390,elevation:0,attackCooldown:0,protection:0,spawnVersion:self.spawnVersion+1});Object.assign(victim,{x:950,y:1430,elevation:0,health:100,protection:0,spawnVersion:victim.spawnVersion+1});await a.waitForTimeout(300);await a.keyboard.press('f');await a.waitForTimeout(250);assert.equal(victim.health,75);await b.waitForFunction(()=>document.querySelector('.game-hud')?.textContent.includes('75 / 100'));await a.keyboard.press('Escape');
 Object.assign(self,{x:1030,y:1130,elevation:0,spawnVersion:self.spawnVersion+1});Object.assign(victim,{x:1170,y:780,elevation:90,health:100,spawnVersion:victim.spawnVersion+1});await a.reload();await a.locator('.viewport canvas').waitFor();await a.waitForTimeout(450);assert.equal(room.players.length,2);assert.equal(await a.locator('.viewport canvas').getAttribute('data-map-id'),'vikings_fjord');await a.locator('.viewport canvas').click();await a.waitForFunction(()=>!!document.pointerLockElement);await fjordDirection(0);await a.keyboard.press('Escape');await a.waitForTimeout(350);await a.screenshot({path:resolve(output,'VIKING_FJORD_PREVIEW.png'),fullPage:true});
 Object.assign(victim,{x:1100,y:1450,elevation:0,spawnVersion:victim.spawnVersion+1});await b.reload();await b.locator('.viewport canvas').waitFor();await b.waitForTimeout(300);assert.equal(await b.locator('.viewport canvas').getAttribute('data-map-id'),'vikings_fjord');const vj=await b.locator('.joystick').boundingBox(),vv=await b.locator('.viewport').boundingBox(),vs=await b.getByRole('button',{name:'Sprint',exact:true}).boundingBox(),vl={id:41,x:vj.x+vj.width/2,y:vj.y+vj.height/2-30},vr={id:42,x:vv.x+vv.width*.8,y:vv.y+vv.height*.4},vp={id:43,x:vs.x+vs.width/2,y:vs.y+vs.height/2};const priorFjord={x:victim.x,y:victim.y};await mobile.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[vl,vr,vp]});vr.x+=25;await mobile.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[vl,vr,vp]});for(let wait=0;wait<20&&Math.hypot(victim.x-priorFjord.x,victim.y-priorFjord.y)<=5;wait++)await b.waitForTimeout(100);await mobile.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert(Math.hypot(victim.x-priorFjord.x,victim.y-priorFjord.y)>5);assert(victim.stamina<100);await b.getByRole('button',{name:'Dash',exact:true}).tap();await b.waitForTimeout(150);assert(victim.dashCooldown>0);await b.getByRole('button',{name:'Attack',exact:true}).tap();await b.waitForTimeout(150);assert(victim.attackCooldown>0);await checkLayout(b);await b.screenshot({path:resolve(output,'VIKING_FJORD_MOBILE_PREVIEW.png'),fullPage:true});
 for(const [width,height] of sizes){await a.setViewportSize({width,height});await a.waitForTimeout(60);await checkLayout(a);}
 game.rooms.tick(room.round.endsAt);room.nextMapId='outlaws_canyon';room.nextMapVariant=null;game.rooms.tick(room.round.returnAt);room.round.endsAt=Date.now()+90000;for(const page of [a,b]){await page.waitForFunction(()=>document.querySelector('.viewport canvas')?.dataset.mapId==='outlaws_canyon');assert.equal(await page.locator('.minimap').count(),1);assert.equal(await page.locator('.minimap-title').textContent(),"OUTLAW'S CANYON N ↑");await checkLayout(page);}game.rooms.tick(room.round.endsAt);await a.getByRole('heading',{name:'MATCH COMPLETE',exact:true}).waitFor();assert.deepEqual(room.match.mapHistory,['central_plaza','vikings_fjord','outlaws_canyon']);
 await (room.hostId===self.id?a:b).getByRole('button',{name:'Return everyone to lobby'}).click();await a.getByRole('button',{name:'Ready up'}).waitFor();assert.equal(room.mapId,'central_plaza');assert.equal(room.mapVariant,null);
 assert.deepEqual(errors,[]);console.log('Browser QA passed: two independent sessions, WebGL render, forward/sprint/dash, turn, reticle melee, synchronized health, refresh, Central Plaza minimap/elevated traversal, pointer-lock stationary yaw/pitch and steering, real multi-touch joystick/look, 11 viewport sizes without overflow or clipped HUD, three-round authoritative map rotation, Scorched Point traversal/combat/touch/reconnect, clean scene replacement, final results, lobby reset, Aerie day/night shared rendering, stair climb and reconnect, Canyon porch/melee/dash/minimap/mobile/reconnect and variant cleanup; Viking fortress/cave/dock traversal, combat, touch controls, reconnect, minimap, 11 viewport sizes and transition-away cleanup.');
}finally{if(browser)await browser.close();await game.close();}
