import React, {useEffect, useRef, useState} from 'react';
import {MAX_PLAYERS, type ClientMessage, type RoomView} from '../shared/game';
import {MATCH, ROUND} from '../shared/rounds';
import {COMBAT} from '../shared/combat';
import {MAPS} from '../shared/map';
import {OPENING_MAP_ID} from '../shared/map-rotation';
import './entry.css';
import {ControlsGuide, ControlSymbol} from './ControlsGuide';

type Props={room:RoomView|null;id:string;name:string;code:string;status:string;latency:number|null;pending:boolean;setName:(s:string)=>void;setCode:(s:string)=>void;action:(m:ClientMessage)=>void;canStart:boolean};
type IconName='player'|'target'|'copy'|'check'|'arrow'|'lock'|'controls'|'signal'|'crown';
export function Icon({name}:{name:IconName}){return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" aria-hidden="true">{name==='player'?<><circle cx="12" cy="7" r="4"/><path d="M4 22v-3a8 8 0 0 1 16 0v3Z"/></>:name==='target'?<><circle cx="12" cy="12" r="8"/><circle cx="12" cy="12" r="3"/><path d="M12 0v7m0 10v7M0 12h7m10 0h7"/></>:name==='copy'?<><rect x="8" y="6" width="12" height="15" rx="1"/><path d="M15 3H4v15"/></>:name==='check'?<path d="m4 12 5 5L21 5"/>:name==='arrow'?<path d="M3 12h18m-7-7 7 7-7 7"/>:name==='lock'?<><rect x="5" y="10" width="14" height="11"/><path d="M8 10V6a4 4 0 0 1 8 0v4"/><path d="M12 14v3"/></>:name==='controls'?<><rect x="2" y="5" width="20" height="14" rx="2"/><path d="M5 9h2m2 0h2m2 0h2m2 0h2M5 13h2m2 0h2m2 0h2m2 0h2M7 16h10"/></>:name==='signal'?<path d="M4 20v-4m5 4v-8m5 8V8m5 12V4"/>:<path d="m2 6 5 5 5-8 5 8 5-5-3 13H5Z"/>}</svg>}
function CodeSlots({code}:{code:string}){return <span className="code-slots" aria-hidden="true">{Array.from({length:6},(_,i)=><span key={i}>{code[i]||''}</span>)}</span>}
function Brand(){return <div className="entry-brand" aria-label="Bounty Shift"><div className="entry-wordmark">B<Icon name="target"/>UNTY <em>SHIFT</em></div><p>MULTIPLAYER // CENTRAL PLAZA</p></div>}
export function EntryFlow({room,id,name,code,status,latency,pending,setName,setCode,action,canStart}:Props){
 const [drawer,setDrawer]=useState<'help'|'controls'|null>(null),[copied,setCopied]=useState(false),[copyError,setCopyError]=useState('');
 const [coarse,setCoarse]=useState(()=>matchMedia('(pointer:coarse)').matches);
 const ready=room?.players.find(p=>p.id===id)?.ready,host=room?.hostId===id,online=status==='Connected';
 const previousPhase=useRef(room?.phase);
 useEffect(()=>{const media=matchMedia('(pointer:coarse)');const update=()=>setCoarse(media.matches);media.addEventListener('change',update);return()=>media.removeEventListener('change',update);},[]);
 useEffect(()=>{if(previousPhase.current!==room?.phase){setDrawer(null);setCopied(false);}previousPhase.current=room?.phase;},[room?.phase]);
 useEffect(()=>{if(!copied)return;const t=setTimeout(()=>setCopied(false),2000);return()=>clearTimeout(t);},[copied]);
 const copy=async()=>{if(!room)return;setCopyError('');try{if(navigator.clipboard?.writeText)await navigator.clipboard.writeText(room.code);else{const field=document.createElement('textarea');field.value=room.code;field.style.position='fixed';field.style.opacity='0';document.body.append(field);field.select();const ok=document.execCommand('copy');field.remove();if(!ok)throw Error();}setCopied(true);}catch{setCopyError(`Could not copy. Room code: ${room.code}. Select it to copy manually.`);}};
 const locked=pending||!online;
 // The server always opens round one on OPENING_MAP_ID; subsequent rounds use its existing random rotation.
 const opening=MAPS[OPENING_MAP_ID];
 return <>
  <div className={`entry-atmosphere ${room?'lobby-atmosphere':''}`} aria-hidden="true"><div className="entry-rain"/><div className="entry-searchlight"/></div>
  <header className="entry-header"><Brand/><div className={`entry-network ${online?'online':''}`} role="status"><span className="network-dot"/><b>{online?'ONLINE':status.toUpperCase()}</b>{online&&latency!==null&&<span>{latency} MS</span>}<Icon name="signal"/></div></header>
  {!room?<section className="entry-login terminal" aria-labelledby="login-title">
   <div className="login-intro"><h2 id="login-title">HUNT YOUR <span>TARGET.</span></h2><p>Every player has a mark.<br/>Eliminate yours before someone eliminates you.</p></div>
   <form onSubmit={e=>{e.preventDefault();if(!locked&&name.trim())action({type:'create',name});}}>
    <label className="entry-field" htmlFor="display-name"><span className="field-icon"><Icon name="player"/></span><span className="field-content"><span>DISPLAY NAME</span><input id="display-name" maxLength={20} value={name} onChange={e=>setName(e.target.value)} placeholder="Enter your display name..." autoComplete="nickname" required/></span></label>
    <button className="entry-primary create-room" disabled={locked||!name.trim()} type="submit">CREATE ROOM<Icon name="arrow"/></button>
   </form>
   <div className="entry-divider"><span>OR</span></div>
   <form className="join-form" onSubmit={e=>{e.preventDefault();if(!locked&&name.trim()&&code.trim().length===6)action({type:'join',name,code});}}>
    <label className="entry-label" htmlFor="room-code">ROOM CODE</label>
    <div className="join-line"><div className="slot-input"><CodeSlots code={code}/><input id="room-code" aria-label="Room code" maxLength={6} value={code} onChange={e=>setCode(e.target.value.replace(/\s/g,'').toUpperCase())} autoCapitalize="characters" autoComplete="off" spellCheck={false} /></div><button className="entry-secondary join-room" type="submit" disabled={locked||!name.trim()||code.trim().length!==6}>JOIN</button></div>
   </form>
   <button aria-label="HOW TO PLAY" className="entry-secondary login-help" onClick={()=>setDrawer('help')}><span className="question">?</span>HOW TO PLAY</button>
  </section>:<>
   <section className="entry-lobby terminal" aria-labelledby="lobby-title">
    <div className="lobby-heading"><div><h2 id="lobby-title">PRIVATE LOBBY <span className="heading-slash">/</span></h2><p>HUNT YOUR TARGET. ELIMINATE YOUR MARK. MOST BOUNTIES WINS.</p></div><div className="occupancy"><div>PLAYERS <b>{room.players.filter(p=>p.connected).length} / {MAX_PLAYERS}</b></div><div className="occupancy-dots" aria-hidden="true">{Array.from({length:MAX_PLAYERS},(_,i)=><i className={i<room.players.filter(p=>p.connected).length?'occupied':''} key={i}/>)}</div></div></div>
    <div className="lobby-columns"><div className="lobby-left">
     <div className="room-code-area"><span className="entry-label">ROOM CODE</span><div className="room-code-line"><span className="code" data-room-code={room.code} aria-label={`Room code ${room.code}`}><CodeSlots code={room.code}/><span className="sr-only">{room.code}</span></span><button className="entry-secondary" onClick={copy}><Icon name={copied?'check':'copy'}/>{copied?'COPIED':'COPY'}</button></div><p className="copy-feedback" role="status">{copyError||'Share this code with another player.'}</p></div>
     <h3 className="entry-label players-title">PLAYERS</h3><ul className="lobby-player-list">{Array.from({length:MAX_PLAYERS},(_,i)=>{const p=room.players[i];return <li key={p?.id??`empty-${i}`} className={`${p?'occupied-player':'empty-player'} ${p?.id===id?'local-player':''}`}><span className="lobby-avatar" style={p?{color:p.color}:undefined}><Icon name="player"/></span>{p?<><span className="lobby-player-name">{p.name}{p.id===id&&<em> (you)</em>}</span>{p.id===room.hostId&&<span className="host-badge"><Icon name="crown"/>HOST</span>}<span className={`ready-state ${p.ready&&p.connected?'is-ready':''}`}><i/>{!p.connected?'RECONNECTING':p.ready?'READY':'NOT READY'}</span></>:<><span className="lobby-player-name">WAITING FOR PLAYER...</span><span className="ready-state"><i/>—</span></>}</li>})}</ul>
     <div className="lobby-requirements"><span className={room.players.filter(p=>p.connected).length>=2?'met':''}><i>{room.players.filter(p=>p.connected).length>=2?'✓':''}</i>2+ PLAYERS</span><span className={room.players.every(p=>p.ready&&p.connected)?'met':''}><i>{room.players.every(p=>p.ready&&p.connected)?'✓':''}</i>ALL PLAYERS READY</span></div>
    </div><div className="lobby-right">
     <section className="map-preview"><div className="map-preview-label"><span className="entry-label">CURRENT MAP</span><h3>{opening.name.toUpperCase()}</h3><span>OPENING ROUND · RANDOM ROTATION FOLLOWS</span></div><img src="/assets/central-plaza-preview.webp" alt="In-game view of Central Plaza, the opening round map"/><div className="map-metadata"><span>◐ NIGHT</span><span>{2}–{MAX_PLAYERS} PLAYERS</span><span>{room.match.totalRounds} ROUNDS</span><span>{ROUND.durationMs/1000} SEC / ROUND</span></div></section>
     <section className="lobby-objective"><Icon name="target"/><div><h3>OBJECTIVE</h3><p>Hunt your assigned target.<br/>Eliminate your mark to earn a bounty.<br/>Most bounties after {room.match.totalRounds} rounds wins.</p></div><div className="lobby-secondary-actions"><button aria-label="HOW TO PLAY" className="entry-secondary" onClick={()=>setDrawer('help')}>? HOW TO PLAY</button><button className="entry-secondary" onClick={()=>setDrawer('controls')}><Icon name="controls"/>CONTROLS</button></div></section>
     <section className="match-settings"><h3>MATCH SETTINGS</h3><dl><dt>MAP</dt><dd>{opening.name} → Random rotation</dd><dt>ROUNDS</dt><dd>{room.match.totalRounds}</dd><dt>TIME</dt><dd>{ROUND.durationMs/1000} SEC / ROUND</dd><dt>PLAYERS</dt><dd>2–{MAX_PLAYERS}</dd></dl></section>
    </div></div>
    {room.notice&&<p className="lobby-notice" role="status">{room.notice.replace(/\btest\b/gi,'match')}</p>}
    <div className="lobby-bottom-actions"><button className="entry-primary" disabled={locked} onClick={()=>action({type:'ready',ready:!ready})}><Icon name="check"/>{ready?'CANCEL READY':'READY UP'}</button>{host&&canStart?<button className="entry-primary" disabled={locked} onClick={()=>action({type:'start'})}><Icon name="arrow"/>START MATCH</button>:<div className="lobby-waiting" role="status"><Icon name="lock"/><div><strong>{canStart?'WAITING FOR HOST':room.players.filter(p=>p.connected).length<2?'WAITING FOR PLAYERS':'WAITING FOR READY'}</strong><span>{host?'HOST CAN START WHEN REQUIREMENTS ARE MET':canStart?'THE HOST WILL START THE MATCH':'2+ CONNECTED PLAYERS · EVERYONE READY'}</span></div></div>}</div>
   </section><button className="leave-lobby entry-secondary" disabled={!online||pending} onClick={()=>action({type:'leave'})}>← LEAVE LOBBY</button>
  </>}
  {drawer&&<EntryDrawer kind={drawer} coarse={coarse} rounds={room?.match.totalRounds??MATCH.rounds} close={()=>setDrawer(null)}/>}
 </>;
}
function EntryDrawer({kind,coarse,rounds,close}:{kind:'help'|'controls';coarse:boolean;rounds:number;close:()=>void}){
 const ref=useRef<HTMLElement>(null);
 useEffect(()=>{const previous=document.activeElement as HTMLElement|null;ref.current?.querySelector<HTMLButtonElement>('button')?.focus();const handle=(e:KeyboardEvent)=>{if(e.key==='Escape'){e.preventDefault();close();}if(e.key==='Tab'){const nodes=ref.current?.querySelectorAll<HTMLElement>('button,a,input,[tabindex="0"]');if(!nodes?.length)return;const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}};document.addEventListener('keydown',handle);return()=>{document.removeEventListener('keydown',handle);previous?.focus();};},[kind]);
 return <div className={`entry-drawer-backdrop ${kind==='controls'?'controls-backdrop':''}`} onPointerDown={e=>{if(e.target===e.currentTarget)close();}}><aside className={`entry-drawer ${kind==='controls'?'controls-drawer':''}`} ref={ref} role="dialog" aria-modal="true" aria-labelledby="drawer-title">{kind==='controls'?<><div className="controls-header"><h2 id="drawer-title"><ControlSymbol name="book"/>CONTROLS</h2><button className="controls-close" onClick={close} aria-label="Close panel">×</button></div><ControlsGuide coarse={coarse}/></>:<><button className="drawer-close entry-secondary" onClick={close} aria-label="Close panel">✕ CLOSE</button><span className="entry-label">BOUNTY SHIFT // FIELD GUIDE</span><h2 id="drawer-title">HOW TO PLAY</h2><div className="help-content"><h3>YOUR MARK. YOUR BOUNTY.</h3><p>Every player receives a private target. Only eliminating your assigned target earns a bounty. Eliminating another player earns no bounty. Your target changes after a successful elimination.</p><h3>WIN THE MATCH</h3><p>Play {rounds} rounds of {ROUND.durationMs/1000} seconds. Round scores reset; your match total carries forward. The highest total wins. Ties share the win. After each round, play pauses for {ROUND.resultsMs/1000} seconds while standings appear. The next round starts automatically. Final results stay visible until the host returns everyone to the lobby.</p><h3>STAY IN THE HUNT</h3><p>Attacks are close-range strikes aimed at the center reticle. Walls block hits. Players have {COMBAT.maxHealth} health and strikes deal {COMBAT.damage} damage. After a knockout, respawn in {COMBAT.respawnDelay} seconds with brief protection. Attacking ends your protection.</p><h3>ENTER A MATCH</h3><p>Share the room code. At least two connected players must be in the room, and everyone must ready up. The host starts the match. Central Plaza opens the match; later rounds rotate randomly through the existing maps.</p></div></>}</aside></div>;
}
