import React from 'react';
import {MODES,validTeams,type GameMode} from '../shared/modes';
import type {RoomView,ClientMessage} from '../shared/game';
import './modes.css';
export function ModeLobby({room,host,locked,action}:{room:RoomView;host:boolean;locked:boolean;action:(m:ClientMessage)=>void}){
 return <section className="mode-selector"><div className="mode-heading"><h3>♛ GAME MODE <small>{host?'HOST ONLY':'HOST SELECTS'}</small></h3><p>Choose the game mode for this 3-round match. Maps rotate independently.</p></div><div className="mode-cards">{(Object.keys(MODES) as GameMode[]).map(mode=>{const rule=MODES[mode],selected=room.selectedGameMode===mode;return <article key={mode} className={`mode-card ${selected?'selected':''}`}>
 <button className="mode-select" disabled={!host||locked} aria-label={`Select ${rule.name}`} aria-pressed={selected} onClick={()=>action({type:'settings',mode,format:room.selectedFormat})}><div className={`mode-art art-${mode}`} aria-hidden="true"><span>{rule.icon}</span><i/><i/></div><span className="mode-name">{rule.icon} {rule.name}</span><span className="selected-badge">{selected?'SELECTED':'AVAILABLE'}</span><span className="mode-description">{{tag:'Avoid being IT at zero. Freeze runners to escape.',flag_run:'Loot, recover the flag, and deliver it to the capture zone.',kill_race:'Most eliminations wins. Duos race to 15.'}[mode]}</span></button>
 <div className="format-buttons">{(['solo','duo'] as const).map(format=><button disabled={!host||locked} key={format} aria-pressed={selected&&room.selectedFormat===format} onClick={()=>action({type:'settings',mode,format})}>{format==='solo'?'●':'●●'} {format.toUpperCase()}</button>)}</div></article>;})}</div>
 <div className="mode-settings"><section><h3>MATCH SETTINGS</h3><dl><div><dt>ROUNDS</dt><dd>3</dd></div><div><dt>ROUND TIME</dt><dd>90 SEC</dd></div><div><dt>PLAYERS</dt><dd>2–6</dd></div><div><dt>FORMAT</dt><dd>{room.selectedFormat.toUpperCase()}</dd></div></dl><p>{room.selectedFormat==='solo'?'Every player competes individually.': 'Teams of two · 4 or 6 players · no friendly fire'}</p>{!validTeams(room.selectedFormat,room.players.length)&&room.selectedFormat==='duo'&&<p className="format-warning" role="status">DUO NEEDS 4 OR 6 PLAYERS</p>}</section><section className="rotation-preview"><h3>MAP ROTATION <small>RANDOM</small></h3><img src="/assets/central-plaza-preview.webp" alt="Central Plaza opening map"/><p>Central Plaza opens. Random maps follow.</p></section></div></section>;
}
